CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -Isrc -Isrc/lexer -Isrc/parser -Isrc/ast -Isrc/codegen -Isrc/semantic

# Lamo runtime is maintained as a real .h file (src/codegen/lamo_runtime.h)
# and embedded into the compiler binary as a C string. The string file is
# auto-generated by scripts/embed_runtime.py and committed to the repo so
# contributors without Python can still build.
RUNTIME_HEADER = src/codegen/lamo_runtime.h
RUNTIME_DATA   = src/codegen/lamo_runtime_data.c

SRCS = src/lamo_v2.c src/lexer/lexer.c src/parser/parser.c src/ast/ast.c src/codegen/codegen.c src/semantic/semantic.c $(RUNTIME_DATA)
OBJS = $(SRCS:.c=.o)

ifeq ($(OS),Windows_NT)
EXEEXT = .exe
else
EXEEXT =
endif

TARGET = lamo$(EXEEXT)

.PHONY: all clean test embed-runtime

all: $(TARGET)

# Re-embed the runtime whenever the header changes.
embed-runtime: $(RUNTIME_DATA)

$(RUNTIME_DATA): $(RUNTIME_HEADER) scripts/embed_runtime.py
	@command -v python3 >/dev/null 2>&1 && python3 scripts/embed_runtime.py || \
	 command -v python  >/dev/null 2>&1 && python  scripts/embed_runtime.py || \
	 echo "warning: python not found; using stale $(RUNTIME_DATA)"

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
ifeq ($(OS),Windows_NT)
	@del /q /f $(OBJS) $(TARGET) *.c.output lamo_exec.c lamo_exec.exe lamo.exe 2>nul || echo done
else
	rm -f $(OBJS) $(TARGET) *.c.output lamo_exec.c lamo_exec lamo.exe
endif

test: $(TARGET)
ifeq ($(OS),Windows_NT)
	powershell -ExecutionPolicy Bypass -File tests/run_tests.ps1
else
	sh tests/run_tests.sh ./$(TARGET)
endif
