CC = gcc
# Sprint 2 fix: -O2 for performance, -g for debuggability (gdb, addr2line).
# Both flags are harmless in combination; -O2 lets the compiler inline the
# many static helpers in lamo_runtime.h, and -g preserves source-level
# debugging through the AST/codegen pipeline.
# Sprint 5: -Isrc/cli added so the new cli/*.h headers are found after the
# lamo_v2.c / lampm.c split.
CFLAGS = -Wall -Wextra -std=c99 -O2 -g -Isrc -Isrc/lexer -Isrc/parser -Isrc/ast -Isrc/codegen -Isrc/semantic -Isrc/eval -Isrc/lampm -Isrc/cli

# Sprint 3 fix: link the compiler itself with -lm, because codegen.c now
# uses fmod() directly for constant folding of float % expressions. The
# generated programs are also linked with -lm (see src/lamo_v2.c).
LDFLAGS = -lm

# Lamo runtime is maintained as a real .h file (src/codegen/lamo_runtime.h)
# and embedded into the compiler binary as a C string. The string file is
# auto-generated by scripts/embed_runtime.py and committed to the repo so
# contributors without Python can still build.
RUNTIME_HEADER = src/codegen/lamo_runtime.h
RUNTIME_DATA   = src/codegen/lamo_runtime_data.c

# lampm.c is the integrated package manager (originally a separate
# LamoPacketManager binary). It now compiles into the main `lamo`
# executable and is reachable through `lamo install`, `lamo update`, etc.
# modules.c backs the Sprint 4 namespaced-import feature (`import "..." as alias;`).
#
# Sprint 5 refactor: lamo_v2.c and lampm.c were split into focused
# modules under src/cli/ and src/lampm/. The new .c files implement
# CLI parsing / import resolution / subcommand dispatch / compile
# pipeline (src/cli/) and string/fs / manifest / lockfile / git helpers
# (src/lampm/). The slim lamo_v2.c now only contains main() + run_argv();
# the slim lampm.c only contains lampm_main + per-command handlers.
SRCS = src/lamo_v2.c \
       src/cli/cli_options.c src/cli/paths.c src/cli/import_resolver.c \
       src/cli/commands.c src/cli/compile.c src/cli/help.c \
       src/lexer/lexer.c src/parser/parser.c src/ast/ast.c \
       src/codegen/codegen.c src/semantic/semantic.c src/eval/eval.c \
       src/lampm/lampm.c src/lampm/lampm_util.c src/lampm/lampm_manifest.c \
       src/lampm/lampm_lockfile.c src/lampm/lampm_git.c \
       src/modules.c $(RUNTIME_DATA)
OBJS = $(SRCS:.c=.o)

ifeq ($(OS),Windows_NT)
EXEEXT = .exe
else
EXEEXT =
endif

TARGET = lamo$(EXEEXT)

.PHONY: all clean test embed-runtime

all: $(TARGET)

# Re-embed the runtime whenever the header changes.
embed-runtime: $(RUNTIME_DATA)

$(RUNTIME_DATA): $(RUNTIME_HEADER) scripts/embed_runtime.py
	@command -v python3 >/dev/null 2>&1 && python3 scripts/embed_runtime.py || \
	 command -v python  >/dev/null 2>&1 && python  scripts/embed_runtime.py || \
	 echo "warning: python not found; using stale $(RUNTIME_DATA)"

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDFLAGS)

# Sprint 4 fix: header dependencies. The old pattern rule `%.o: %.c` only
# tracked .c mtime, so editing a shared header (lexer.h, ast.h, builtins.h,
# error_util.h, etc.) would NOT rebuild the .o files that included it —
# leading to silent ABI skew (e.g. enum value shifts) that produced wrong
# codegen. We now list the headers each .c file transitively includes, so
# `make` does the right thing on header edits. Generated lamo_runtime_data.c
# has no extra deps beyond itself.
#
# Sprint 5: also track the new cli/ and lampm/ internal headers so
# editing them triggers a rebuild of every .c that includes them.
SRCS_DEP_H = src/lexer/lexer.h src/parser/parser.h src/ast/ast.h \
             src/builtins.h src/error_util.h src/semantic/semantic.h \
             src/codegen/codegen.h src/codegen/lamo_runtime_data.h \
             src/codegen/lamo_runtime.h src/eval/eval.h \
             src/lampm/lampm.h src/lampm/lampm_internal.h src/modules.h \
             src/cli/cli_options.h src/cli/paths.h src/cli/import_resolver.h \
             src/cli/commands.h src/cli/compile.h src/cli/help.h

%.o: %.c $(SRCS_DEP_H)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
ifeq ($(OS),Windows_NT)
	@del /q /f $(OBJS) $(TARGET) *.c.output lamo_exec.c lamo_exec.exe lamo.exe 2>nul || echo done
else
	rm -f $(OBJS) $(TARGET) *.c.output lamo_exec.c lamo_exec lamo.exe
endif

test: $(TARGET)
ifeq ($(OS),Windows_NT)
	powershell -ExecutionPolicy Bypass -File tests/run_tests.ps1
else
	sh tests/run_tests.sh ./$(TARGET)
endif
