/*
 * lampm_lockfile.c — lamo.lock lockfile load / write / mutate.
 * See lampm_internal.h for the overall design.
 *
 * Refactor (Sprint 5): these functions used to be `static` inside the
 * 2400-line lampm.c. They are now external so that the per-command
 * handlers (in lampm.c) and install_dependency can call them.
 *
 * Lockfile format:
 *
 *     # Comment
 *     alias = repo @ ref : commit
 *
 * repo is required; ref defaults to "HEAD"; commit is optional (NULL
 * when the install couldn't resolve a commit hash).
 */

#define _DEFAULT_SOURCE
#define _POSIX_C_SOURCE 200809L

#include "lampm_internal.h"

void lockfile_init(Lockfile* lock) {
    memset(lock, 0, sizeof(*lock));
}

void lockfile_free(Lockfile* lock) {
    size_t i;
    for (i = 0; i < lock->count; i++) {
        free(lock->entries[i].alias);
        free(lock->entries[i].repo);
        free(lock->entries[i].ref);
        free(lock->entries[i].commit);
    }
    free(lock->entries);
    lockfile_init(lock);
}

int lockfile_ensure_capacity(Lockfile* lock, size_t required) {
    LockEntry* resized;
    size_t new_capacity;

    if (required <= lock->capacity) {
        return 1;
    }

    new_capacity = lock->capacity > 0 ? lock->capacity * 2 : 4;
    while (new_capacity < required) {
        new_capacity *= 2;
    }

    resized = realloc(lock->entries, sizeof(LockEntry) * new_capacity);
    if (!resized) {
        return 0;
    }
    lock->entries = resized;
    lock->capacity = new_capacity;
    return 1;
}

const LockEntry* lockfile_find(const Lockfile* lock, const char* alias) {
    size_t i;
    for (i = 0; i < lock->count; i++) {
        if (strcmp(lock->entries[i].alias, alias) == 0) {
            return &lock->entries[i];
        }
    }
    return NULL;
}

int lockfile_set(Lockfile* lock, const char* alias, const char* repo,
                 const char* ref, const char* commit) {
    LockEntry* entry = NULL;
    size_t i;
    char* repo_copy;
    char* ref_copy;
    char* commit_copy;

    for (i = 0; i < lock->count; i++) {
        if (strcmp(lock->entries[i].alias, alias) == 0) {
            entry = &lock->entries[i];
            break;
        }
    }

    repo_copy = lampm_duplicate_string(repo);
    ref_copy = ref ? lampm_duplicate_string(ref) : lampm_duplicate_string("HEAD");
    commit_copy = commit ? lampm_duplicate_string(commit) : NULL;

    if (!repo_copy || !ref_copy || (commit && !commit_copy)) {
        free(repo_copy);
        free(ref_copy);
        free(commit_copy);
        return 0;
    }

    if (entry) {
        free(entry->repo);
        free(entry->ref);
        free(entry->commit);
        entry->repo = repo_copy;
        entry->ref = ref_copy;
        entry->commit = commit_copy;
        return 1;
    }

    if (!lockfile_ensure_capacity(lock, lock->count + 1)) {
        free(repo_copy);
        free(ref_copy);
        free(commit_copy);
        return 0;
    }

    entry = &lock->entries[lock->count++];
    entry->alias = lampm_duplicate_string(alias);
    entry->repo = repo_copy;
    entry->ref = ref_copy;
    entry->commit = commit_copy;
    return entry->alias != NULL;
}

int lockfile_load(const char* path, Lockfile* lock) {
    FILE* file = fopen(path, "r");
    char line[2048];

    lockfile_init(lock);
    if (!file) {
        return 0;
    }

    while (fgets(line, sizeof(line), file)) {
        char* trimmed = trim_whitespace(line);
        char* key;
        char* value;
        char* at;
        char* ref_start;
        char* commit_start;

        if (*trimmed == '\0' || *trimmed == '#') {
            continue;
        }

        if (!split_key_value(trimmed, &key, &value)) {
            continue;
        }

        /* Format: alias = repo @ ref : commit
         * All of ref/commit are optional; only repo is required. */
        at = strchr(value, '@');
        if (at) {
            *at = '\0';
            ref_start = trim_whitespace(at + 1);
        } else {
            ref_start = NULL;
        }

        commit_start = strchr(ref_start ? ref_start : value, ':');
        if (commit_start) {
            *commit_start = '\0';
            commit_start = trim_whitespace(commit_start + 1);
        }

        {
            char* repo = trim_whitespace(value);
            char* ref = ref_start;
            char* commit = commit_start;
            lockfile_set(lock, key, repo, ref, commit);
        }
    }

    fclose(file);
    return 1;
}

int lockfile_write(const char* path, const Lockfile* lock) {
    FILE* file = fopen(path, "w");
    size_t i;

    if (!file) {
        error_msg("failed to write %s: %s", path, strerror(errno));
        return 0;
    }

    fprintf(file, "# Lamo lockfile. Auto-generated by `lampm`. Do not edit by hand.\n");
    fprintf(file, "# Records the exact commit hash installed for each dependency,\n");
    fprintf(file, "# so `lampm install` (no args) reproduces the same checkout.\n");

    for (i = 0; i < lock->count; i++) {
        fprintf(file, "%s = %s @ %s",
                lock->entries[i].alias,
                lock->entries[i].repo,
                lock->entries[i].ref ? lock->entries[i].ref : "HEAD");
        if (lock->entries[i].commit) {
            fprintf(file, " : %s", lock->entries[i].commit);
        }
        fprintf(file, "\n");
    }

    fclose(file);
    return 1;
}
