/*
 * lamo_runtime_data.c - AUTO-GENERATED. Do not edit by hand.
 *
 * Regenerate with: python3 scripts/embed_runtime.py
 *
 * Contains the Lamo runtime (from lamo_runtime.h) as an escaped C
 * string. The codegen emits this verbatim at the top of every
 * generated .c program, replacing ~600 lines of fprintf() calls.
 */

#include "lamo_runtime_data.h"

const char lamo_runtime_source[] =
    "#ifndef LAMO_RUNTIME_H\n#define LAMO_RUNTIME_H\n\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include"
    " <math.h>   /* fmod() \20024 usado por lamo_mod() para operandos float */\n\n#if defined(__GNUC__) || defined(__clang__)"
    "\n#define LAMO_UNUSED __attribute__((unused))\n#else\n#define LAMO_UNUSED\n#endif\n\n/* --------------------------------"
    "---------------------------------- */\n/* 1. Value runtime (always present)                                  */\n/* ----"
    "-------------------------------------------------------------- */\n\ntypedef enum {\n    LAMO_VALUE_INT,\n    LAMO_VALUE"
    "_FLOAT,\n    LAMO_VALUE_STRING,\n    LAMO_VALUE_BOOL,\n    LAMO_VALUE_ARRAY,  /* Sprint 3: [1, 2, 3] - array of LamoValu"
    "es */\n    /* Phase 2: a struct value is stored as a LamoArray under the hood -\n     * field 0 is at items[0], field 1 "
    "at items[1], etc. We use a separate\n     * type tag so the printer can render it differently and so the\n     * semanti"
    "c/codegen can tell struct-typed values from raw arrays at\n     * runtime (useful for debugging and for printing). */\n "
    "   LAMO_VALUE_STRUCT\n} LamoValueType;\n\n/* Sprint 3: forward-declare LamoArray so we can reference it from inside\n * "
    "the LamoValue struct. The full definition appears after LamoValue. */\nstruct LamoArray;\n\ntypedef struct {\n    LamoVa"
    "lueType type;\n    long long int_value;\n    double float_value;\n    const char* string_value;\n    /* Sprint 3: only s"
    "et when type == LAMO_VALUE_ARRAY. Pointer to a\n     * heap-allocated LamoArray; the array is owned by the arena. */\n  "
    "  struct LamoArray* array_value;\n} LamoValue;\n\n/* Sprint 3: LamoArray \20024 a growable array of LamoValues.\n *\n * "
    "Memory model: arrays are heap-allocated and tracked in the string\n * arena (lamo_string_arena). They're freed at progra"
    "m exit via the\n * atexit handler. We reuse the arena rather than introducing a\n * separate arena because:\n *   - the "
    "arena already exists and works\n *   - arrays and strings have the same lifetime (program exit)\n *   - long-running pro"
    "grams already have a documented arena-growth\n *     limitation; arrays inherit that same limitation\n *\n * Each LamoAr"
    "ray owns its `items` buffer. Pushing may realloc the\n * buffer; the array struct itself is fixed-location once allocate"
    "d\n * (so LamoValue.array_value pointers stay valid). */\ntypedef struct LamoArray {\n    LamoValue* items;\n    long lo"
    "ng count;\n    long long capacity;\n} LamoArray;\n\nstatic LAMO_UNUSED LamoValue lamo_make_int(long long value) {\n    L"
    "amoValue result;\n    result.type = LAMO_VALUE_INT;\n    result.int_value = value;\n    result.float_value = 0.0;\n    r"
    "esult.string_value = NULL;\n    result.array_value = NULL;\n    return result;\n}\n\nstatic LAMO_UNUSED LamoValue lamo_m"
    "ake_float(double value) {\n    LamoValue result;\n    result.type = LAMO_VALUE_FLOAT;\n    result.int_value = 0;\n    re"
    "sult.float_value = value;\n    result.string_value = NULL;\n    result.array_value = NULL;\n    return result;\n}\n\nsta"
    "tic LAMO_UNUSED LamoValue lamo_make_bool(int value) {\n    LamoValue result;\n    result.type = LAMO_VALUE_BOOL;\n    re"
    "sult.int_value = value ? 1 : 0;\n    result.float_value = 0.0;\n    result.string_value = NULL;\n    result.array_value "
    "= NULL;\n    return result;\n}\n\nstatic LAMO_UNUSED LamoValue lamo_make_string(const char* value) {\n    LamoValue resu"
    "lt;\n    result.type = LAMO_VALUE_STRING;\n    result.int_value = 0;\n    result.float_value = 0.0;\n    result.string_v"
    "alue = value ? value : \"\";\n    result.array_value = NULL;\n    return result;\n}\n\n/* Sprint 3: make an array value "
    "from an existing LamoArray pointer.\n * The LamoArray must already be heap-allocated (lamo_array_alloc).\n * The LamoVal"
    "ue does NOT take ownership - the arena tracks the array\n * and frees it at exit. */\nstatic LAMO_UNUSED LamoValue lamo_"
    "make_array(LamoArray* array) {\n    LamoValue result;\n    result.type = LAMO_VALUE_ARRAY;\n    result.int_value = 0;\n "
    "   result.float_value = 0.0;\n    result.string_value = NULL;\n    result.array_value = array;\n    return result;\n}\n"
    "\n/* Phase 2: make a struct value. Structs reuse the LamoArray layout -\n * each field occupies one slot in items[]. The"
    " distinct type tag lets\n * the printer render `Player { name: \"x\", hp: 10 }` differently from\n * `[ \"x\", 10 ]`, bu"
    "t the memory model is identical. */\nstatic LAMO_UNUSED LamoValue lamo_make_struct(LamoArray* array) {\n    LamoValue re"
    "sult;\n    result.type = LAMO_VALUE_STRUCT;\n    result.int_value = 0;\n    result.float_value = 0.0;\n    result.string"
    "_value = NULL;\n    result.array_value = array;\n    return result;\n}\n\n/* ---- String arena -------------------------"
    "-------------------------\n * The Lamo runtime has no GC and no per-LamoValue ownership tracking.\n * Strings allocated "
    "dynamically (concatenation, input_str, ...) are\n * registered in this arena and freed all at once on program exit via\n"
    " * atexit(). This fixes the classic leak in loops that concatenate:\n * before, each `s = s + \"x\"` leaked the previous"
    " buffer; now every\n * buffer is tracked and freed on shutdown.\n *\n * Sprint 3: the arena now holds void* (not just ch"
    "ar*) so it can also\n * track LamoArray structs and their internal `items` buffers. All\n * allocations share the same l"
    "ifetime (program exit), so one arena is\n * enough.\n *\n * Known limitation: long-running programs (e.g. HTTP servers) "
    "see the\n * arena grow while they run. This is acceptable for an educational\n * prototype and is documented in the READ"
    "ME.\n */\nstatic void** lamo_string_arena = NULL;\nstatic size_t lamo_string_arena_count = 0;\nstatic size_t lamo_string"
    "_arena_capacity = 0;\n\nstatic LAMO_UNUSED void* lamo_arena_alloc(size_t length) {\n    void* block;\n    if (lamo_strin"
    "g_arena_count == lamo_string_arena_capacity) {\n        size_t new_cap = lamo_string_arena_capacity ? lamo_string_arena_"
    "capacity * 2 : 16;\n        void** new_arena = realloc(lamo_string_arena, sizeof(void*) * new_cap);\n        if (!new_ar"
    "ena) { fprintf(stderr, \"runtime error: string arena exhausted\\n\"); exit(1); }\n        lamo_string_arena = new_arena;"
    "\n        lamo_string_arena_capacity = new_cap;\n    }\n    block = malloc(length);\n    if (!block) { fprintf(stderr, "
    "\"runtime error: failed to allocate string\\n\"); exit(1); }\n    lamo_string_arena[lamo_string_arena_count++] = block;"
    "\n    return block;\n}\n\nstatic LAMO_UNUSED char* lamo_arena_strdup(const char* value) {\n    size_t length;\n    char*"
    " copy;\n    if (!value) { value = \"\"; }\n    length = strlen(value);\n    copy = (char*)lamo_arena_alloc(length + 1);"
    "\n    memcpy(copy, value, length + 1);\n    return copy;\n}\n\nstatic LAMO_UNUSED void lamo_arena_free_all(void) {\n    "
    "size_t i;\n    for (i = 0; i < lamo_string_arena_count; i++) {\n        /* Sprint 3: arena entries may be char* (string "
    "buffers), LamoArray*\n         * (array structs), or LamoValue* (array items buffers). We can't\n         * tell them ap"
    "art at free time, but free() works on all of them. */\n        free(lamo_string_arena[i]);\n    }\n    free(lamo_string_"
    "arena);\n    lamo_string_arena = NULL;\n    lamo_string_arena_count = 0;\n    lamo_string_arena_capacity = 0;\n}\n\nstat"
    "ic LAMO_UNUSED char* lamo_heap_strdup(const char* value) {\n    size_t length;\n    char* copy;\n    if (!value) { value"
    " = \"\"; }\n    length = strlen(value);\n    copy = malloc(length + 1);\n    if (!copy) {\n        fprintf(stderr, \"run"
    "time error: failed to allocate string\\n\");\n        exit(1);\n    }\n    memcpy(copy, value, length + 1);\n    return "
    "copy;\n}\n\nstatic LAMO_UNUSED void lamo_runtime_type_error(const char* message) {\n    fprintf(stderr, \"runtime error:"
    " %s\\n\", message);\n    exit(1);\n}\n\n/* Coer\347\343o: int/float interoperam; string n\343o. */\nstatic LAMO_UNUSED l"
    "ong long lamo_as_int(LamoValue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        lamo_runtime_type_error(\"e"
    "xpected int-compatible value, got string\");\n    }\n    if (value.type == LAMO_VALUE_FLOAT) {\n        return (long lon"
    "g)value.float_value;\n    }\n    return value.int_value;\n}\n\nstatic LAMO_UNUSED double lamo_as_float(LamoValue value) "
    "{\n    if (value.type == LAMO_VALUE_STRING) {\n        lamo_runtime_type_error(\"expected number, got string\");\n    }"
    "\n    if (value.type == LAMO_VALUE_FLOAT) {\n        return value.float_value;\n    }\n    return (double)value.int_valu"
    "e;\n}\n\nstatic LAMO_UNUSED const char* lamo_as_cstring(LamoValue value) {\n    if (value.type != LAMO_VALUE_STRING) {\n"
    "        lamo_runtime_type_error(\"expected string value\");\n    }\n    return value.string_value ? value.string_value :"
    " \"\";\n}\n\nstatic LAMO_UNUSED char* lamo_value_to_owned_string(LamoValue value) {\n    char buffer[64];\n    if (value"
    ".type == LAMO_VALUE_STRING) {\n        return lamo_heap_strdup(lamo_as_cstring(value));\n    }\n    if (value.type == LA"
    "MO_VALUE_FLOAT) {\n        snprintf(buffer, sizeof(buffer), \"%g\", value.float_value);\n        return lamo_heap_strdup"
    "(buffer);\n    }\n    if (value.type == LAMO_VALUE_BOOL) {\n        return lamo_heap_strdup(value.int_value ? \"true\" :"
    " \"false\");\n    }\n    if (value.type == LAMO_VALUE_ARRAY || value.type == LAMO_VALUE_STRUCT) {\n        /* Recursivel"
    "y render the array/struct into a heap string. We\n         * build a temporary buffer, then strdup it. The capacity grow"
    "s\n         * as needed. */\n        size_t cap = 64;\n        size_t len = 0;\n        char* out = (char*)malloc(cap);"
    "\n        if (!out) return lamo_heap_strdup(\"\");\n        out[0] = '\\0';\n        #define LAMO_APPEND_STR(s) do { "
    "\\\n            size_t addlen = strlen(s); \\\n            if (len + addlen + 1 > cap) { \\\n                while (len "
    "+ addlen + 1 > cap) cap *= 2; \\\n                char* grown = (char*)realloc(out, cap); \\\n                if (!grown"
    ") { free(out); return lamo_heap_strdup(\"\"); } \\\n                out = grown; \\\n            } \\\n            memcp"
    "y(out + len, s, addlen); \\\n            len += addlen; \\\n            out[len] = '\\0'; \\\n        } while (0)\n     "
    "   LAMO_APPEND_STR(value.type == LAMO_VALUE_STRUCT ? \"{ \" : \"[\");\n        if (value.array_value) {\n            lon"
    "g long i;\n            for (i = 0; i < value.array_value->count; i++) {\n                if (i > 0) LAMO_APPEND_STR(\", "
    "\");\n                char* elem = lamo_value_to_owned_string(value.array_value->items[i]);\n                LAMO_APPEND"
    "_STR(elem);\n                free(elem);\n            }\n        }\n        LAMO_APPEND_STR(value.type == LAMO_VALUE_STR"
    "UCT ? \" }\" : \"]\");\n        #undef LAMO_APPEND_STR\n        return out;\n    }\n    snprintf(buffer, sizeof(buffer),"
    " \"%lld\", value.int_value);\n    return lamo_heap_strdup(buffer);\n}\n\nstatic LAMO_UNUSED LamoValue lamo_concat_values"
    "(LamoValue left, LamoValue right) {\n    char* left_text = lamo_value_to_owned_string(left);\n    char* right_text = lam"
    "o_value_to_owned_string(right);\n    size_t left_length = strlen(left_text);\n    size_t right_length = strlen(right_tex"
    "t);\n    char* combined = (char*)lamo_arena_alloc(left_length + right_length + 1);\n    memcpy(combined, left_text, left"
    "_length);\n    memcpy(combined + left_length, right_text, right_length + 1);\n    free(left_text);\n    free(right_text)"
    ";\n    return lamo_make_string(combined);\n}\n\n/*\n * Truthiness (DOCUMENTED \20024 see README \"Truthiness\" section):"
    "\n *\n *   - int:     non-zero is true\n *   - float:   non-zero is true (0.0 is false)\n *   - bool:    the value itsel"
    "f\n *   - string:  non-empty is true (\"\" is false)\n *\n * This is Python-like truthiness, NOT Rust-like strict bool. "
    "`if (5)` and\n * `if (\"abc\")` are both valid and true. `if (0)` and `if (\"\")` are false.\n */\nstatic LAMO_UNUSED in"
    "t lamo_is_truthy(LamoValue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        return value.string_value && va"
    "lue.string_value[0] != '\\0';\n    }\n    if (value.type == LAMO_VALUE_FLOAT) {\n        return value.float_value != 0.0"
    ";\n    }\n    if (value.type == LAMO_VALUE_ARRAY) {\n        /* Sprint 3: arrays are truthy if non-empty. */\n        re"
    "turn value.array_value != NULL && value.array_value->count > 0;\n    }\n    if (value.type == LAMO_VALUE_STRUCT) {\n    "
    "    /* Phase 2: a struct value is always truthy (even an empty one\n         * represents a constructed object). */\n   "
    "     return value.array_value != NULL;\n    }\n    return value.int_value != 0;\n}\n\nstatic LAMO_UNUSED void lamo_print"
    "_value(LamoValue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        printf(\"%s\\n\", value.string_value ? va"
    "lue.string_value : \"\");\n    } else if (value.type == LAMO_VALUE_FLOAT) {\n        printf(\"%g\\n\", value.float_value"
    ");\n    } else if (value.type == LAMO_VALUE_ARRAY) {\n        /* Sprint 3: print arrays in Python-like [a, b, c] form. E"
    "ach\n         * element is printed via its own lamo_value_to_owned_string\n         * representation so strings show wit"
    "hout quotes (matching\n         * the existing `print` semantics for top-level values). */\n        long long i;\n      "
    "  printf(\"[\");\n        if (value.array_value) {\n            for (i = 0; i < value.array_value->count; i++) {\n      "
    "          if (i > 0) printf(\", \");\n                /* Reuse lamo_value_to_owned_string to format each element. */\n  "
    "              char* text = lamo_value_to_owned_string(value.array_value->items[i]);\n                printf(\"%s\", text"
    ");\n                free(text);\n            }\n        }\n        printf(\"]\\n\");\n    } else if (value.type == LAMO_"
    "VALUE_STRUCT) {\n        /* Phase 2: print structs in `S { v0, v1, ... }` form. We don't\n         * know the struct's t"
    "ype name at runtime (that info lives in the\n         * compiler), so we just print the values. This matches what\n     "
    "    * `print(player)` does for a Player{hp:10, name:\"x\"} - the user\n         * typically prints specific fields (`pri"
    "nt(player.hp)`) rather\n         * than the whole struct. */\n        long long i;\n        printf(\"{ \");\n        if "
    "(value.array_value) {\n            for (i = 0; i < value.array_value->count; i++) {\n                if (i > 0) printf("
    "\", \");\n                char* text = lamo_value_to_owned_string(value.array_value->items[i]);\n                printf("
    "\"%s\", text);\n                free(text);\n            }\n        }\n        printf(\" }\\n\");\n    } else {\n       "
    " printf(\"%lld\\n\", value.int_value);\n    }\n}\n\n/* -----------------------------------------------------------------"
    "- */\n/* Sprint 3: Array runtime                                            */\n/* -------------------------------------"
    "----------------------------- */\n\n/* Allocate a new LamoArray with the given initial capacity. The struct\n * is regis"
    "tered in the arena; its `items` buffer is also arena-tracked\n * (so it survives until program exit). */\nstatic LAMO_UN"
    "USED LamoArray* lamo_array_alloc(long long initial_capacity) {\n    LamoArray* array;\n    if (initial_capacity < 4) ini"
    "tial_capacity = 4;\n    array = (LamoArray*)lamo_arena_alloc(sizeof(LamoArray));\n    array->items = (LamoValue*)lamo_ar"
    "ena_alloc(sizeof(LamoValue) * (size_t)initial_capacity);\n    array->count = 0;\n    array->capacity = initial_capacity;"
    "\n    return array;\n}\n\n/* Build an array value from a list of LamoValues. Used by the codegen\n * for array literals."
    " The values are copied into a new buffer. */\nstatic LAMO_UNUSED LamoValue lamo_array_from_values(LamoValue* values, lon"
    "g long count) {\n    long long i;\n    LamoArray* array = lamo_array_alloc(count > 0 ? count : 4);\n    for (i = 0; i < "
    "count; i++) {\n        array->items[i] = values[i];\n    }\n    array->count = count;\n    return lamo_make_array(array)"
    ";\n}\n\n/* Get element at index. Negative indices count from the end (-1 is the\n * last element). Out-of-range indices "
    "abort with a clear runtime error. */\nstatic LAMO_UNUSED LamoValue lamo_array_get(LamoValue array_val, long long index) "
    "{\n    LamoArray* array;\n    if (array_val.type != LAMO_VALUE_ARRAY) {\n        lamo_runtime_type_error(\"expected arra"
    "y value for indexing\");\n    }\n    array = array_val.array_value;\n    if (!array) {\n        lamo_runtime_type_error("
    "\"indexed array is NULL (internal error)\");\n    }\n    if (index < 0) index += array->count;  /* Python-like negative "
    "index */\n    if (index < 0 || index >= array->count) {\n        fprintf(stderr, \"runtime error: array index %lld out o"
    "f bounds (array length %lld)\\n\",\n                index, array->count);\n        exit(1);\n    }\n    return array->it"
    "ems[index];\n}\n\n/* Returns the length of an array. */\nstatic LAMO_UNUSED LamoValue lamo_array_len(LamoValue array_val"
    ") {\n    if (array_val.type != LAMO_VALUE_ARRAY) {\n        lamo_runtime_type_error(\"expected array value for len()\");"
    "\n    }\n    if (!array_val.array_value) {\n        return lamo_make_int(0);\n    }\n    return lamo_make_int(array_val."
    "array_value->count);\n}\n\n/* Push a value onto the end of the array. Grows the internal buffer if\n * needed via reallo"
    "c (the new buffer is registered in the arena; the old\n * one is leaked until program exit, same as the existing string-"
    "arena\n * policy). Returns 0 on success. */\nstatic LAMO_UNUSED LamoValue lamo_array_push(LamoValue array_val, LamoValue"
    " value) {\n    LamoArray* array;\n    if (array_val.type != LAMO_VALUE_ARRAY) {\n        lamo_runtime_type_error(\"expec"
    "ted array value for push()\");\n    }\n    array = array_val.array_value;\n    if (!array) {\n        lamo_runtime_type_"
    "error(\"push() target array is NULL (internal error)\");\n    }\n    if (array->count == array->capacity) {\n        lon"
    "g long new_cap = array->capacity * 2;\n        LamoValue* new_items = (LamoValue*)lamo_arena_alloc(sizeof(LamoValue) * ("
    "size_t)new_cap);\n        memcpy(new_items, array->items, sizeof(LamoValue) * (size_t)array->count);\n        array->ite"
    "ms = new_items;\n        array->capacity = new_cap;\n    }\n    array->items[array->count++] = value;\n    return lamo_m"
    "ake_int(0);\n}\n\n/* Pop the last element from the array and return it. Aborts if the\n * array is empty. */\nstatic LAM"
    "O_UNUSED LamoValue lamo_array_pop(LamoValue array_val) {\n    LamoArray* array;\n    LamoValue popped;\n    if (array_va"
    "l.type != LAMO_VALUE_ARRAY) {\n        lamo_runtime_type_error(\"expected array value for pop()\");\n    }\n    array = "
    "array_val.array_value;\n    if (!array || array->count == 0) {\n        fprintf(stderr, \"runtime error: pop() on empty "
    "array\\n\");\n        exit(1);\n    }\n    popped = array->items[--array->count];\n    return popped;\n}\n\n/* Phase 2: "
    "array index assignment \20024 `arr[i] = value`.\n * Returns the assigned value (so it can be used in expressions, e.g.\n"
    " * `let old = (arr[0] = 42);` though that's not idiomatic). */\nstatic LAMO_UNUSED LamoValue lamo_array_set(LamoValue ar"
    "ray_val, long long index, LamoValue value) {\n    LamoArray* array;\n    if (array_val.type != LAMO_VALUE_ARRAY) {\n    "
    "    lamo_runtime_type_error(\"expected array value for index assignment\");\n    }\n    array = array_val.array_value;\n"
    "    if (!array) {\n        lamo_runtime_type_error(\"index-assign target array is NULL (internal error)\");\n    }\n    "
    "if (index < 0) index += array->count;\n    if (index < 0 || index >= array->count) {\n        fprintf(stderr, \"runtime "
    "error: array index %lld out of bounds in assignment (array length %lld)\\n\",\n                index, array->count);\n  "
    "      exit(1);\n    }\n    array->items[index] = value;\n    return value;\n}\n\n/* Phase 2: struct helpers. Structs reu"
    "se LamoArray under the hood.\n *\n * lamo_struct_alloc(n) - create a struct value with n zero-initialized\n *   fields ("
    "each slot is lamo_make_int(0)).\n * lamo_struct_get(sval, i) - read field at index i (lamo_array_get works\n *   too, bu"
    "t this function emits a clearer error message).\n * lamo_struct_set(sval, i, value) - write field at index i. Returns th"
    "e\n *   assigned value (so it can be used in expressions). */\nstatic LAMO_UNUSED LamoValue lamo_struct_alloc(long long "
    "field_count) {\n    long long i;\n    LamoArray* array;\n    if (field_count < 0) field_count = 0;\n    array = lamo_arr"
    "ay_alloc(field_count > 0 ? field_count : 4);\n    for (i = 0; i < field_count; i++) {\n        array->items[i] = lamo_ma"
    "ke_int(0);\n    }\n    array->count = field_count;\n    return lamo_make_struct(array);\n}\n\nstatic LAMO_UNUSED LamoVal"
    "ue lamo_struct_get(LamoValue struct_val, long long index) {\n    LamoArray* array;\n    if (struct_val.type != LAMO_VALU"
    "E_STRUCT) {\n        lamo_runtime_type_error(\"expected struct value for field access\");\n    }\n    array = struct_val"
    ".array_value;\n    if (!array) {\n        lamo_runtime_type_error(\"field access on NULL struct (internal error)\");\n  "
    "  }\n    if (index < 0 || index >= array->count) {\n        fprintf(stderr, \"runtime error: struct field index %lld out"
    " of bounds (field count %lld)\\n\",\n                index, array->count);\n        exit(1);\n    }\n    return array->i"
    "tems[index];\n}\n\nstatic LAMO_UNUSED LamoValue lamo_struct_set(LamoValue struct_val, long long index, LamoValue value) "
    "{\n    LamoArray* array;\n    if (struct_val.type != LAMO_VALUE_STRUCT) {\n        lamo_runtime_type_error(\"expected st"
    "ruct value for field assignment\");\n    }\n    array = struct_val.array_value;\n    if (!array) {\n        lamo_runtime"
    "_type_error(\"field-assign target struct is NULL (internal error)\");\n    }\n    if (index < 0 || index >= array->count"
    ") {\n        fprintf(stderr, \"runtime error: struct field index %lld out of bounds in assignment (field count %lld)\\n"
    "\",\n                index, array->count);\n        exit(1);\n    }\n    array->items[index] = value;\n    return value;"
    "\n}\n\n/* Opera\347\365es aritm\351ticas: se qualquer operando for float, resultado \351 float. */\nstatic LAMO_UNUSED L"
    "amoValue lamo_add(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_STRING || right.type == LAMO_VALUE"
    "_STRING) {\n        return lamo_concat_values(left, right);\n    }\n    if (left.type == LAMO_VALUE_FLOAT || right.type "
    "== LAMO_VALUE_FLOAT) {\n        return lamo_make_float(lamo_as_float(left) + lamo_as_float(right));\n    }\n    return l"
    "amo_make_int(lamo_as_int(left) + lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_sub(LamoValue left, LamoVa"
    "lue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_float"
    "(lamo_as_float(left) - lamo_as_float(right));\n    }\n    return lamo_make_int(lamo_as_int(left) - lamo_as_int(right));"
    "\n}\n\nstatic LAMO_UNUSED LamoValue lamo_mul(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT |"
    "| right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_float(lamo_as_float(left) * lamo_as_float(right));\n    }"
    "\n    return lamo_make_int(lamo_as_int(left) * lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_div(LamoValu"
    "e left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        double l"
    "hs = lamo_as_float(left);\n        double rhs = lamo_as_float(right);\n        if (rhs == 0.0) {\n            fprintf(st"
    "derr, \"runtime error: division by zero\\n\");\n            exit(1);\n        }\n        return lamo_make_float(lhs / rh"
    "s);\n    }\n    {\n        long long lhs = lamo_as_int(left);\n        long long rhs = lamo_as_int(right);\n        if ("
    "rhs == 0) {\n            fprintf(stderr, \"runtime error: division by zero\\n\");\n            exit(1);\n        }\n    "
    "    return lamo_make_int(lhs / rhs);\n    }\n}\n\nstatic LAMO_UNUSED LamoValue lamo_mod(LamoValue left, LamoValue right)"
    " {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        double lhs = lamo_as_float(left)"
    ";\n        double rhs = lamo_as_float(right);\n        if (rhs == 0.0) {\n            fprintf(stderr, \"runtime error: m"
    "odulo by zero\\n\");\n            exit(1);\n        }\n        return lamo_make_float(fmod(lhs, rhs));\n    }\n    {\n  "
    "      long long lhs = lamo_as_int(left);\n        long long rhs = lamo_as_int(right);\n        if (rhs == 0) {\n        "
    "    fprintf(stderr, \"runtime error: modulo by zero\\n\");\n            exit(1);\n        }\n        return lamo_make_in"
    "t(lhs % rhs);\n    }\n}\n\nstatic LAMO_UNUSED LamoValue lamo_negate(LamoValue value) {\n    if (value.type == LAMO_VALUE"
    "_FLOAT) return lamo_make_float(-value.float_value);\n    return lamo_make_int(-lamo_as_int(value));\n}\n\nstatic LAMO_UN"
    "USED LamoValue lamo_not(LamoValue value) {\n    return lamo_make_bool(!lamo_is_truthy(value));\n}\n\nstatic LAMO_UNUSED "
    "LamoValue lamo_less(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALU"
    "E_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) < lamo_as_float(right));\n    }\n    return lamo_make_bool"
    "(lamo_as_int(left) < lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_greater(LamoValue left, LamoValue righ"
    "t) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_"
    "float(left) > lamo_as_float(right));\n    }\n    return lamo_make_bool(lamo_as_int(left) > lamo_as_int(right));\n}\n\nst"
    "atic LAMO_UNUSED LamoValue lamo_less_equal(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || "
    "right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) <= lamo_as_float(right));\n    }\n "
    "   return lamo_make_bool(lamo_as_int(left) <= lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_greater_equal"
    "(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n       "
    " return lamo_make_bool(lamo_as_float(left) >= lamo_as_float(right));\n    }\n    return lamo_make_bool(lamo_as_int(left)"
    " >= lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_equal(LamoValue left, LamoValue right) {\n    /* Phase "
    "2: arrays and structs compare by identity (same pointer).\n     * Deep equality would be expensive and surprising for mu"
    "table values. */\n    if (left.type == LAMO_VALUE_ARRAY || left.type == LAMO_VALUE_STRUCT ||\n        right.type == LAMO"
    "_VALUE_ARRAY || right.type == LAMO_VALUE_STRUCT) {\n        if (left.type != right.type) return lamo_make_bool(0);\n    "
    "    return lamo_make_bool(left.array_value == right.array_value);\n    }\n    if (left.type == LAMO_VALUE_STRING || righ"
    "t.type == LAMO_VALUE_STRING) {\n        if (left.type != LAMO_VALUE_STRING || right.type != LAMO_VALUE_STRING) {\n      "
    "      return lamo_make_bool(0);\n        }\n        return lamo_make_bool(strcmp(lamo_as_cstring(left), lamo_as_cstring("
    "right)) == 0);\n    }\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_m"
    "ake_bool(lamo_as_float(left) == lamo_as_float(right));\n    }\n    return lamo_make_bool(lamo_as_int(left) == lamo_as_in"
    "t(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_not_equal(LamoValue left, LamoValue right) {\n    LamoValue result = "
    "lamo_equal(left, right);\n    return lamo_make_bool(!lamo_is_truthy(result));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_an"
    "d(LamoValue left, LamoValue right) {\n    return lamo_make_bool(lamo_is_truthy(left) && lamo_is_truthy(right));\n}\n\nst"
    "atic LAMO_UNUSED LamoValue lamo_or(LamoValue left, LamoValue right) {\n    return lamo_make_bool(lamo_is_truthy(left) ||"
    " lamo_is_truthy(right));\n}\n\nstatic LAMO_UNUSED void lamo_print_prompt(LamoValue prompt) {\n    if (prompt.type == LAM"
    "O_VALUE_STRING) {\n        printf(\"%s\", lamo_as_cstring(prompt));\n    } else if (prompt.type == LAMO_VALUE_FLOAT) {\n"
    "        printf(\"%g\", prompt.float_value);\n    } else {\n        printf(\"%lld\", prompt.int_value);\n    }\n    fflus"
    "h(stdout);\n}\n\n/* input(prompt) - reads an integer from stdin. Kept for compatibility with\n * existing programs. To r"
    "ead strings, use input_str(prompt). */\nstatic LAMO_UNUSED LamoValue lamo_input_value(LamoValue prompt) {\n    long long"
    " value;\n    lamo_print_prompt(prompt);\n    if (scanf(\"%lld\", &value) != 1) {\n        value = 0;\n    }\n    return "
    "lamo_make_int(value);\n}\n\n/* input_int(prompt) - explicit alias for input(), reads long long. */\nstatic LAMO_UNUSED L"
    "amoValue lamo_input_int_value(LamoValue prompt) {\n    long long value;\n    lamo_print_prompt(prompt);\n    if (scanf("
    "\"%lld\", &value) != 1) {\n        value = 0;\n    }\n    return lamo_make_int(value);\n}\n\n/* input_str(prompt) - read"
    "s one line of text from stdin, without the trailing\n * newline. The returned string is allocated in the string arena (f"
    "reed at\n * atexit). */\nstatic LAMO_UNUSED LamoValue lamo_input_str_value(LamoValue prompt) {\n    char buffer[1024];\n"
    "    size_t length;\n    char* owned;\n    lamo_print_prompt(prompt);\n    if (fgets(buffer, sizeof(buffer), stdin) == NU"
    "LL) {\n        buffer[0] = '\\0';\n    }\n    length = strlen(buffer);\n    while (length > 0 && (buffer[length-1] == '"
    "\\n' || buffer[length-1] == '\\r')) {\n        buffer[--length] = '\\0';\n    }\n    owned = lamo_arena_strdup(buffer);"
    "\n    return lamo_make_string(owned);\n}\n\nstatic LAMO_UNUSED LamoValue lamo_isnumber_value(LamoValue value) {\n    ret"
    "urn lamo_make_bool(value.type == LAMO_VALUE_INT || value.type == LAMO_VALUE_FLOAT);\n}\n\nstatic LAMO_UNUSED LamoValue l"
    "amo_isstring_value(LamoValue value) {\n    return lamo_make_bool(value.type == LAMO_VALUE_STRING);\n}\n\nstatic LAMO_UNU"
    "SED LamoValue lamo_abs_value(LamoValue value) {\n    if (value.type == LAMO_VALUE_FLOAT) {\n        double v = value.flo"
    "at_value;\n        return lamo_make_float(v < 0 ? -v : v);\n    }\n    {\n        long long raw = lamo_as_int(value);\n "
    "       return lamo_make_int(raw < 0 ? -raw : raw);\n    }\n}\n\n/* -----------------------------------------------------"
    "------------- */\n/* 2. GUI runtime (only emitted when the program uses gui_* builtins) */\n/* -------------------------"
    "----------------------------------------- */\n#ifdef LAMO_NEEDS_GUI_RUNTIME\n\n#ifdef _WIN32\n#include <windows.h>\n\nty"
    "pedef struct {\n    HWND hwnd;\n    HDC back_dc;\n    HBITMAP back_bitmap;\n    HFONT font;\n    int width;\n    int hei"
    "ght;\n    int is_open;\n} LamoGuiState;\n\nstatic LamoGuiState lamo_gui = {0};\nstatic int lamo_gui_registered = 0;\n\ns"
    "tatic LRESULT CALLBACK lamo_gui_window_proc(HWND hwnd, UINT message, WPARAM w_param, LPARAM l_param) {\n    (void)l_para"
    "m;\n    switch (message) {\n        case WM_CLOSE:\n            lamo_gui.is_open = 0;\n            DestroyWindow(hwnd);"
    "\n            return 0;\n        case WM_DESTROY:\n            lamo_gui.is_open = 0;\n            PostQuitMessage(0);\n "
    "           return 0;\n        default:\n            return DefWindowProcA(hwnd, message, w_param, l_param);\n    }\n}\n"
    "\nstatic void lamo_gui_process_messages(void) {\n    MSG message;\n    while (PeekMessageA(&message, NULL, 0, 0, PM_REMO"
    "VE)) {\n        if (message.message == WM_QUIT) {\n            lamo_gui.is_open = 0;\n        }\n        TranslateMessag"
    "e(&message);\n        DispatchMessageA(&message);\n    }\n}\n\nstatic int lamo_gui_open(int width, int height, const cha"
    "r* title) {\n    WNDCLASSA window_class;\n    HDC window_dc;\n    RECT rect;\n    if (lamo_gui.is_open) { return 1; }\n "
    "   if (!lamo_gui_registered) {\n        ZeroMemory(&window_class, sizeof(window_class));\n        window_class.lpfnWndPr"
    "oc = lamo_gui_window_proc;\n        window_class.hInstance = GetModuleHandleA(NULL);\n        window_class.lpszClassName"
    " = \"LamoGuiWindow\";\n        window_class.hCursor = LoadCursor(NULL, IDC_ARROW);\n        window_class.hbrBackground ="
    " (HBRUSH)(COLOR_WINDOW + 1);\n        if (!RegisterClassA(&window_class)) {\n            DWORD error_code = GetLastError"
    "();\n            if (error_code != ERROR_CLASS_ALREADY_EXISTS) {\n                fprintf(stderr, \"failed to register G"
    "UI window class (error %lu)\\n\", (unsigned long)error_code);\n                return 0;\n            }\n        }\n    "
    "    lamo_gui_registered = 1;\n    }\n    lamo_gui.width = width;\n    lamo_gui.height = height;\n    rect.left = 0; rect"
    ".top = 0; rect.right = width; rect.bottom = height;\n    AdjustWindowRect(&rect, WS_OVERLAPPEDWINDOW, 0);\n    lamo_gui."
    "hwnd = CreateWindowExA(0, \"LamoGuiWindow\", title, WS_OVERLAPPEDWINDOW,\n        CW_USEDEFAULT, CW_USEDEFAULT, rect.rig"
    "ht - rect.left, rect.bottom - rect.top,\n        NULL, NULL, GetModuleHandleA(NULL), NULL);\n    if (!lamo_gui.hwnd) { f"
    "printf(stderr, \"failed to create GUI window\\n\"); return 0; }\n    ShowWindow(lamo_gui.hwnd, SW_SHOW);\n    UpdateWind"
    "ow(lamo_gui.hwnd);\n    window_dc = GetDC(lamo_gui.hwnd);\n    lamo_gui.back_dc = CreateCompatibleDC(window_dc);\n    la"
    "mo_gui.back_bitmap = CreateCompatibleBitmap(window_dc, width, height);\n    SelectObject(lamo_gui.back_dc, lamo_gui.back"
    "_bitmap);\n    ReleaseDC(lamo_gui.hwnd, window_dc);\n    SetBkMode(lamo_gui.back_dc, TRANSPARENT);\n    lamo_gui.font = "
    "CreateFontA(24, 0, 0, 0, FW_NORMAL, 0, 0, 0, ANSI_CHARSET,\n        OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_Q"
    "UALITY,\n        DEFAULT_PITCH | FF_DONTCARE, \"Segoe UI\");\n    if (lamo_gui.font) { SelectObject(lamo_gui.back_dc, la"
    "mo_gui.font); }\n    lamo_gui.is_open = 1;\n    return 1;\n}\n\nstatic int lamo_gui_should_close(void) {\n    lamo_gui_p"
    "rocess_messages();\n    return lamo_gui.is_open ? 0 : 1;\n}\n\nstatic void lamo_gui_begin_frame(int r, int g, int b) {\n"
    "    RECT rect; HBRUSH brush;\n    if (!lamo_gui.is_open) return;\n    rect.left = 0; rect.top = 0; rect.right = lamo_gui"
    ".width; rect.bottom = lamo_gui.height;\n    brush = CreateSolidBrush(RGB(r, g, b));\n    FillRect(lamo_gui.back_dc, &rec"
    "t, brush);\n    DeleteObject(brush);\n}\n\nstatic void lamo_gui_draw_rect(int x, int y, int width, int height, int r, in"
    "t g, int b) {\n    RECT rect; HBRUSH brush;\n    if (!lamo_gui.is_open) return;\n    rect.left = x; rect.top = y; rect.r"
    "ight = x + width; rect.bottom = y + height;\n    brush = CreateSolidBrush(RGB(r, g, b));\n    FillRect(lamo_gui.back_dc,"
    " &rect, brush);\n    DeleteObject(brush);\n}\n\nstatic void lamo_gui_draw_text(const char* text, int x, int y, int r, in"
    "t g, int b) {\n    if (!lamo_gui.is_open) return;\n    SetTextColor(lamo_gui.back_dc, RGB(r, g, b));\n    TextOutA(lamo_"
    "gui.back_dc, x, y, text, (int)strlen(text));\n}\n\nstatic void lamo_gui_end_frame(void) {\n    HDC window_dc;\n    if (!"
    "lamo_gui.is_open) return;\n    window_dc = GetDC(lamo_gui.hwnd);\n    BitBlt(window_dc, 0, 0, lamo_gui.width, lamo_gui.h"
    "eight, lamo_gui.back_dc, 0, 0, SRCCOPY);\n    ReleaseDC(lamo_gui.hwnd, window_dc);\n}\n\nstatic void lamo_gui_close(void"
    ") {\n    if (lamo_gui.font) { DeleteObject(lamo_gui.font); lamo_gui.font = NULL; }\n    if (lamo_gui.back_bitmap) { Dele"
    "teObject(lamo_gui.back_bitmap); lamo_gui.back_bitmap = NULL; }\n    if (lamo_gui.back_dc) { DeleteDC(lamo_gui.back_dc); "
    "lamo_gui.back_dc = NULL; }\n    if (lamo_gui.hwnd) { DestroyWindow(lamo_gui.hwnd); lamo_gui.hwnd = NULL; }\n    lamo_gui"
    ".is_open = 0;\n}\n#elif defined(__unix__) || defined(__unix) || defined(__linux__) || defined(__APPLE__)\n/* Backend X11"
    " for Linux/Mac. C and Xlib are trivial to link (-lX11). */\n#include <X11/Xlib.h>\n#include <X11/Xutil.h>\n#include <X11"
    "/Xos.h>\n\ntypedef struct {\n    Display* display;\n    Window window;\n    GC gc;\n    Pixmap back_pixmap;\n    XFontSt"
    "ruct* font;\n    int width;\n    int height;\n    int is_open;\n    Atom wm_delete;\n} LamoGuiState;\n\nstatic LamoGuiSt"
    "ate lamo_gui = {0};\n\nstatic int lamo_gui_open(int width, int height, const char* title) {\n    int screen;\n    if (la"
    "mo_gui.is_open) { return 1; }\n    lamo_gui.display = XOpenDisplay(NULL);\n    if (!lamo_gui.display) {\n        fprintf"
    "(stderr, \"failed to open X11 display\\n\");\n        return 0;\n    }\n    screen = DefaultScreen(lamo_gui.display);\n "
    "   lamo_gui.width = width;\n    lamo_gui.height = height;\n    lamo_gui.window = XCreateSimpleWindow(lamo_gui.display,\n"
    "        RootWindow(lamo_gui.display, screen),\n        0, 0, width, height, 1,\n        BlackPixel(lamo_gui.display, scr"
    "een),\n        WhitePixel(lamo_gui.display, screen));\n    XSelectInput(lamo_gui.display, lamo_gui.window,\n        Expo"
    "sureMask | StructureNotifyMask);\n    XStoreName(lamo_gui.display, lamo_gui.window, title ? title : \"Lamo\");\n    lamo"
    "_gui.wm_delete = XInternAtom(lamo_gui.display, \"WM_DELETE_WINDOW\", False);\n    XSetWMProtocols(lamo_gui.display, lamo"
    "_gui.window, &lamo_gui.wm_delete, 1);\n    lamo_gui.gc = XCreateGC(lamo_gui.display, lamo_gui.window, 0, NULL);\n    lam"
    "o_gui.back_pixmap = XCreatePixmap(lamo_gui.display, lamo_gui.window,\n        width, height, DefaultDepth(lamo_gui.displ"
    "ay, screen));\n    lamo_gui.font = XLoadQueryFont(lamo_gui.display, \"fixed\");\n    if (lamo_gui.font) { XSetFont(lamo_"
    "gui.display, lamo_gui.gc, lamo_gui.font->fid); }\n    XMapWindow(lamo_gui.display, lamo_gui.window);\n    XFlush(lamo_gu"
    "i.display);\n    lamo_gui.is_open = 1;\n    return 1;\n}\n\nstatic void lamo_gui_process_messages(void) {\n    XEvent ev"
    "ent;\n    while (XPending(lamo_gui.display) > 0) {\n        XNextEvent(lamo_gui.display, &event);\n        if (event.typ"
    "e == ClientMessage) {\n            if ((Atom)event.xclient.data.l[0] == lamo_gui.wm_delete) {\n                lamo_gui."
    "is_open = 0;\n            }\n        }\n    }\n}\n\nstatic int lamo_gui_should_close(void) {\n    if (!lamo_gui.display)"
    " return 1;\n    lamo_gui_process_messages();\n    return lamo_gui.is_open ? 0 : 1;\n}\n\nstatic void lamo_gui_begin_fram"
    "e(int r, int g, int b) {\n    XColor color;\n    if (!lamo_gui.is_open) return;\n    color.red = (unsigned short)(r * 25"
    "7);\n    color.green = (unsigned short)(g * 257);\n    color.blue = (unsigned short)(b * 257);\n    color.flags = DoRed "
    "| DoGreen | DoBlue;\n    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);\n    XSetForegroun"
    "d(lamo_gui.display, lamo_gui.gc, color.pixel);\n    XFillRectangle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,"
    "\n        0, 0, lamo_gui.width, lamo_gui.height);\n}\n\nstatic void lamo_gui_draw_rect(int x, int y, int width, int heig"
    "ht, int r, int g, int b) {\n    XColor color;\n    if (!lamo_gui.is_open) return;\n    color.red = (unsigned short)(r * "
    "257);\n    color.green = (unsigned short)(g * 257);\n    color.blue = (unsigned short)(b * 257);\n    color.flags = DoRe"
    "d | DoGreen | DoBlue;\n    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);\n    XSetForegro"
    "und(lamo_gui.display, lamo_gui.gc, color.pixel);\n    XFillRectangle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc"
    ",\n        x, y, width, height);\n}\n\nstatic void lamo_gui_draw_text(const char* text, int x, int y, int r, int g, int "
    "b) {\n    XColor color;\n    if (!lamo_gui.is_open) return;\n    color.red = (unsigned short)(r * 257);\n    color.green"
    " = (unsigned short)(g * 257);\n    color.blue = (unsigned short)(b * 257);\n    color.flags = DoRed | DoGreen | DoBlue;"
    "\n    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);\n    XSetForeground(lamo_gui.display,"
    " lamo_gui.gc, color.pixel);\n    XDrawString(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,\n        x, y + (lamo_"
    "gui.font ? lamo_gui.font->ascent : 12),\n        text ? text : \"\", text ? (int)strlen(text) : 0);\n}\n\nstatic void la"
    "mo_gui_end_frame(void) {\n    if (!lamo_gui.is_open) return;\n    XCopyArea(lamo_gui.display, lamo_gui.back_pixmap, lamo"
    "_gui.window, lamo_gui.gc,\n        0, 0, lamo_gui.width, lamo_gui.height, 0, 0);\n    XFlush(lamo_gui.display);\n}\n\nst"
    "atic void lamo_gui_close(void) {\n    if (lamo_gui.font) { XFreeFont(lamo_gui.display, lamo_gui.font); lamo_gui.font = N"
    "ULL; }\n    if (lamo_gui.back_pixmap) { XFreePixmap(lamo_gui.display, lamo_gui.back_pixmap); lamo_gui.back_pixmap = 0; }"
    "\n    if (lamo_gui.gc) { XFreeGC(lamo_gui.display, lamo_gui.gc); lamo_gui.gc = NULL; }\n    if (lamo_gui.window) { XDest"
    "royWindow(lamo_gui.display, lamo_gui.window); lamo_gui.window = 0; }\n    if (lamo_gui.display) { XCloseDisplay(lamo_gui"
    ".display); lamo_gui.display = NULL; }\n    lamo_gui.is_open = 0;\n}\n#else\nstatic int lamo_gui_open(int width, int heig"
    "ht, const char* title) {\n    (void)width; (void)height; (void)title;\n    fprintf(stderr, \"GUI builtins are not suppor"
    "ted on this platform.\\n\");\n    return 0;\n}\nstatic int lamo_gui_should_close(void) { return 1; }\nstatic void lamo_g"
    "ui_begin_frame(int r, int g, int b) { (void)r; (void)g; (void)b; }\nstatic void lamo_gui_draw_rect(int x, int y, int wid"
    "th, int height, int r, int g, int b) {\n    (void)x; (void)y; (void)width; (void)height; (void)r; (void)g; (void)b;\n}\n"
    "static void lamo_gui_draw_text(const char* text, int x, int y, int r, int g, int b) {\n    (void)text; (void)x; (void)y;"
    " (void)r; (void)g; (void)b;\n}\nstatic void lamo_gui_end_frame(void) {}\nstatic void lamo_gui_close(void) {}\n#endif\n\n"
    "#endif /* LAMO_NEEDS_GUI_RUNTIME */\n\n/* ------------------------------------------------------------------ */\n/* 3. H"
    "TTP runtime (only emitted when the program uses http_* builtins) */\n/* ------------------------------------------------"
    "------------------ */\n#ifdef LAMO_NEEDS_HTTP_RUNTIME\n\n#ifdef _WIN32\n#include <winsock2.h>\n#include <ws2tcpip.h>\nty"
    "pedef SOCKET lamo_socket_t;\n#define LAMO_INVALID_SOCKET INVALID_SOCKET\n#define lamo_close_socket closesocket\n#else\n#"
    "include <sys/types.h>\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <arpa/inet.h>\n#include <unistd.h>\nty"
    "pedef int lamo_socket_t;\n#define LAMO_INVALID_SOCKET (-1)\n#define lamo_close_socket close\n#endif\n\ntypedef struct La"
    "moHttpRoute {\n    char* path;\n    char* body;\n    struct LamoHttpRoute* next;\n} LamoHttpRoute;\n\nstatic LamoHttpRou"
    "te* lamo_http_routes = NULL;\nstatic int lamo_http_runtime_initialized = 0;\n\nstatic int lamo_http_init_runtime(void) {"
    "\n#ifdef _WIN32\n    WSADATA wsa_data;\n    if (!lamo_http_runtime_initialized) {\n        if (WSAStartup(MAKEWORD(2, 2)"
    ", &wsa_data) != 0) {\n            fprintf(stderr, \"failed to initialize Winsock\\n\");\n            return 0;\n        "
    "}\n        lamo_http_runtime_initialized = 1;\n    }\n#else\n    lamo_http_runtime_initialized = 1;\n#endif\n    return "
    "1;\n}\n\nstatic void lamo_http_add_route(const char* path, const char* body) {\n    LamoHttpRoute* route;\n    if (!lamo"
    "_http_init_runtime()) { return; }\n    route = malloc(sizeof(LamoHttpRoute));\n    if (!route) { fprintf(stderr, \"faile"
    "d to allocate HTTP route\\n\"); exit(1); }\n    route->path = lamo_heap_strdup(path);\n    route->body = lamo_heap_strdu"
    "p(body);\n    route->next = lamo_http_routes;\n    lamo_http_routes = route;\n}\n\nstatic const LamoHttpRoute* lamo_http"
    "_find_route(const char* path) {\n    LamoHttpRoute* current = lamo_http_routes;\n    while (current) {\n        if (strc"
    "mp(current->path, path) == 0) { return current; }\n        current = current->next;\n    }\n    return NULL;\n}\n\nstati"
    "c int lamo_http_send_all(lamo_socket_t socket_fd, const char* data, int total_length) {\n    int sent = 0;\n    while (s"
    "ent < total_length) {\n        int chunk = send(socket_fd, data + sent, total_length - sent, 0);\n        if (chunk <= 0"
    ") { return 0; }\n        sent += chunk;\n    }\n    return 1;\n}\n\nstatic int lamo_http_send_response(lamo_socket_t cli"
    "ent_socket, int status_code, const char* body) {\n    char header[512];\n    const char* reason = status_code == 200 ? "
    "\"OK\" : \"Not Found\";\n    int body_length = (int)strlen(body);\n    int header_length = snprintf(header, sizeof(heade"
    "r),\n        \"HTTP/1.1 %d %s\\r\\n\"\n        \"Content-Type: text/plain; charset=utf-8\\r\\n\"\n        \"Content-Leng"
    "th: %d\\r\\n\"\n        \"Connection: close\\r\\n\\r\\n\",\n        status_code, reason, body_length);\n    if (header_l"
    "ength < 0 || !lamo_http_send_all(client_socket, header, header_length)) {\n        return 0;\n    }\n    return lamo_htt"
    "p_send_all(client_socket, body, body_length);\n}\n\nstatic void lamo_http_handle_client(lamo_socket_t client_socket) {\n"
    "    char request[2048];\n    char method[16];\n    char path[1024];\n    int received = recv(client_socket, request, (in"
    "t)sizeof(request) - 1, 0);\n    if (received <= 0) { return; }\n    request[received] = '\\0';\n    method[0] = '\\0';\n"
    "    path[0] = '\\0';\n    if (sscanf(request, \"%15s %1023s\", method, path) == 2) {\n        const LamoHttpRoute* route"
    " = lamo_http_find_route(path);\n        if (route) {\n            lamo_http_send_response(client_socket, 200, route->bod"
    "y);\n            return;\n        }\n    }\n    lamo_http_send_response(client_socket, 404, \"not found\");\n}\n\nstatic"
    " int lamo_http_run_server(int port, int serve_once) {\n    lamo_socket_t server_socket;\n    struct sockaddr_in address;"
    "\n    int opt_value = 1;\n    if (!lamo_http_init_runtime()) { return 0; }\n    server_socket = socket(AF_INET, SOCK_STR"
    "EAM, 0);\n    if (server_socket == LAMO_INVALID_SOCKET) {\n        fprintf(stderr, \"failed to create HTTP socket\\n\");"
    "\n        return 0;\n    }\n    setsockopt(server_socket, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt_value, sizeof(opt_"
    "value));\n    memset(&address, 0, sizeof(address));\n    address.sin_family = AF_INET;\n    address.sin_addr.s_addr = ht"
    "onl(INADDR_LOOPBACK);\n    address.sin_port = htons((unsigned short)port);\n    if (bind(server_socket, (struct sockaddr"
    "*)&address, sizeof(address)) != 0) {\n        fprintf(stderr, \"failed to bind HTTP server on port %d\\n\", port);\n    "
    "    lamo_close_socket(server_socket);\n        return 0;\n    }\n    if (listen(server_socket, 8) != 0) {\n        fprin"
    "tf(stderr, \"failed to listen on HTTP server port %d\\n\", port);\n        lamo_close_socket(server_socket);\n        re"
    "turn 0;\n    }\n    while (1) {\n        lamo_socket_t client_socket = accept(server_socket, NULL, NULL);\n        if (c"
    "lient_socket == LAMO_INVALID_SOCKET) { break; }\n        lamo_http_handle_client(client_socket);\n        lamo_close_soc"
    "ket(client_socket);\n        if (serve_once) { break; }\n    }\n    lamo_close_socket(server_socket);\n    return 1;\n}"
    "\n\n#endif /* LAMO_NEEDS_HTTP_RUNTIME */\n\n#endif /* LAMO_RUNTIME_H */\n"
;
