/*
 * lamo_runtime.h - Runtime C library embedded into every generated Lamo program.
 *
 * BUG #2 FIX: All functions are marked LAMO_UNUSED so that programs which don't
 * use every operation (e.g. don't call lamo_div, lamo_mod, lamo_input_str, ...)
 * don't produce a wall of -Wunused-function warnings under -Wall -Wextra.
 *
 * This is more maintainable than per-program tree-shaking because:
 *   - The runtime is small (~12 KB of source) — bloat in the generated .c is
 *     negligible; the C compiler already eliminates unused static functions.
 *   - We don't have to walk the AST for every builtin to decide what to emit.
 *   - A single source of truth (this file) for the entire runtime.
 *
 * NIT #9 FIX: This file is embedded into the lamo compiler binary as a string
 * constant (see lamo_runtime_data.{c,h}, generated by scripts/embed_runtime.py)
 * and emitted verbatim at the top of every generated .c program. That cuts
 * ~600 lines of fprintf() out of codegen.c and makes the runtime testable in
 * isolation: you can compile this header alone with a test driver.
 *
 * Layout:
 *   1. Value runtime (always emitted — defines LamoValue and core ops)
 *   2. GUI runtime   (emitted only when the program uses gui_* builtins)
 *   3. HTTP runtime  (emitted only when the program uses http_* builtins)
 *
 * The codegen selects (2) and (3) by emitting `#define LAMO_NEEDS_GUI_RUNTIME`
 * and `#define LAMO_NEEDS_HTTP_RUNTIME` before including this content inline.
 */
#ifndef LAMO_RUNTIME_H
#define LAMO_RUNTIME_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>   /* fmod() — usado por lamo_mod() para operandos float */

#if defined(__GNUC__) || defined(__clang__)
#define LAMO_UNUSED __attribute__((unused))
#else
#define LAMO_UNUSED
#endif

/* ------------------------------------------------------------------ */
/* 1. Value runtime (always present)                                  */
/* ------------------------------------------------------------------ */

typedef enum {
    LAMO_VALUE_INT,
    LAMO_VALUE_FLOAT,
    LAMO_VALUE_STRING,
    LAMO_VALUE_BOOL,
    LAMO_VALUE_ARRAY,  /* Sprint 3: [1, 2, 3] - array of LamoValues */
    /* Phase 2: a struct value is stored as a LamoArray under the hood -
     * field 0 is at items[0], field 1 at items[1], etc. We use a separate
     * type tag so the printer can render it differently and so the
     * semantic/codegen can tell struct-typed values from raw arrays at
     * runtime (useful for debugging and for printing). */
    LAMO_VALUE_STRUCT
} LamoValueType;

/* Sprint 3: forward-declare LamoArray so we can reference it from inside
 * the LamoValue struct. The full definition appears after LamoValue. */
struct LamoArray;

typedef struct {
    LamoValueType type;
    long long int_value;
    double float_value;
    const char* string_value;
    /* Sprint 3: only set when type == LAMO_VALUE_ARRAY. Pointer to a
     * heap-allocated LamoArray; the array is owned by the arena. */
    struct LamoArray* array_value;
} LamoValue;

/* Sprint 3: LamoArray — a growable array of LamoValues.
 *
 * Memory model: arrays are heap-allocated and tracked in the string
 * arena (lamo_string_arena). They're freed at program exit via the
 * atexit handler. We reuse the arena rather than introducing a
 * separate arena because:
 *   - the arena already exists and works
 *   - arrays and strings have the same lifetime (program exit)
 *   - long-running programs already have a documented arena-growth
 *     limitation; arrays inherit that same limitation
 *
 * Each LamoArray owns its `items` buffer. Pushing may realloc the
 * buffer; the array struct itself is fixed-location once allocated
 * (so LamoValue.array_value pointers stay valid). */
typedef struct LamoArray {
    LamoValue* items;
    long long count;
    long long capacity;
} LamoArray;

static LAMO_UNUSED LamoValue lamo_make_int(long long value) {
    LamoValue result;
    result.type = LAMO_VALUE_INT;
    result.int_value = value;
    result.float_value = 0.0;
    result.string_value = NULL;
    result.array_value = NULL;
    return result;
}

static LAMO_UNUSED LamoValue lamo_make_float(double value) {
    LamoValue result;
    result.type = LAMO_VALUE_FLOAT;
    result.int_value = 0;
    result.float_value = value;
    result.string_value = NULL;
    result.array_value = NULL;
    return result;
}

static LAMO_UNUSED LamoValue lamo_make_bool(int value) {
    LamoValue result;
    result.type = LAMO_VALUE_BOOL;
    result.int_value = value ? 1 : 0;
    result.float_value = 0.0;
    result.string_value = NULL;
    result.array_value = NULL;
    return result;
}

static LAMO_UNUSED LamoValue lamo_make_string(const char* value) {
    LamoValue result;
    result.type = LAMO_VALUE_STRING;
    result.int_value = 0;
    result.float_value = 0.0;
    result.string_value = value ? value : "";
    result.array_value = NULL;
    return result;
}

/* Sprint 3: make an array value from an existing LamoArray pointer.
 * The LamoArray must already be heap-allocated (lamo_array_alloc).
 * The LamoValue does NOT take ownership - the arena tracks the array
 * and frees it at exit. */
static LAMO_UNUSED LamoValue lamo_make_array(LamoArray* array) {
    LamoValue result;
    result.type = LAMO_VALUE_ARRAY;
    result.int_value = 0;
    result.float_value = 0.0;
    result.string_value = NULL;
    result.array_value = array;
    return result;
}

/* Phase 2: make a struct value. Structs reuse the LamoArray layout -
 * each field occupies one slot in items[]. The distinct type tag lets
 * the printer render `Player { name: "x", hp: 10 }` differently from
 * `[ "x", 10 ]`, but the memory model is identical. */
static LAMO_UNUSED LamoValue lamo_make_struct(LamoArray* array) {
    LamoValue result;
    result.type = LAMO_VALUE_STRUCT;
    result.int_value = 0;
    result.float_value = 0.0;
    result.string_value = NULL;
    result.array_value = array;
    return result;
}

/* ---- String arena --------------------------------------------------
 * The Lamo runtime has no GC and no per-LamoValue ownership tracking.
 * Strings allocated dynamically (concatenation, input_str, ...) are
 * registered in this arena and freed all at once on program exit via
 * atexit(). This fixes the classic leak in loops that concatenate:
 * before, each `s = s + "x"` leaked the previous buffer; now every
 * buffer is tracked and freed on shutdown.
 *
 * Sprint 3: the arena now holds void* (not just char*) so it can also
 * track LamoArray structs and their internal `items` buffers. All
 * allocations share the same lifetime (program exit), so one arena is
 * enough.
 *
 * Known limitation: long-running programs (e.g. HTTP servers) see the
 * arena grow while they run. This is acceptable for an educational
 * prototype and is documented in the README.
 */
static void** lamo_string_arena = NULL;
static size_t lamo_string_arena_count = 0;
static size_t lamo_string_arena_capacity = 0;

static LAMO_UNUSED void* lamo_arena_alloc(size_t length) {
    void* block;
    if (lamo_string_arena_count == lamo_string_arena_capacity) {
        size_t new_cap = lamo_string_arena_capacity ? lamo_string_arena_capacity * 2 : 16;
        void** new_arena = realloc(lamo_string_arena, sizeof(void*) * new_cap);
        if (!new_arena) { fprintf(stderr, "runtime error: string arena exhausted\n"); exit(1); }
        lamo_string_arena = new_arena;
        lamo_string_arena_capacity = new_cap;
    }
    block = malloc(length);
    if (!block) { fprintf(stderr, "runtime error: failed to allocate string\n"); exit(1); }
    lamo_string_arena[lamo_string_arena_count++] = block;
    return block;
}

static LAMO_UNUSED char* lamo_arena_strdup(const char* value) {
    size_t length;
    char* copy;
    if (!value) { value = ""; }
    length = strlen(value);
    copy = (char*)lamo_arena_alloc(length + 1);
    memcpy(copy, value, length + 1);
    return copy;
}

static LAMO_UNUSED void lamo_arena_free_all(void) {
    size_t i;
    for (i = 0; i < lamo_string_arena_count; i++) {
        /* Sprint 3: arena entries may be char* (string buffers), LamoArray*
         * (array structs), or LamoValue* (array items buffers). We can't
         * tell them apart at free time, but free() works on all of them. */
        free(lamo_string_arena[i]);
    }
    free(lamo_string_arena);
    lamo_string_arena = NULL;
    lamo_string_arena_count = 0;
    lamo_string_arena_capacity = 0;
}

static LAMO_UNUSED char* lamo_heap_strdup(const char* value) {
    size_t length;
    char* copy;
    if (!value) { value = ""; }
    length = strlen(value);
    copy = malloc(length + 1);
    if (!copy) {
        fprintf(stderr, "runtime error: failed to allocate string\n");
        exit(1);
    }
    memcpy(copy, value, length + 1);
    return copy;
}

static LAMO_UNUSED void lamo_runtime_type_error(const char* message) {
    fprintf(stderr, "runtime error: %s\n", message);
    exit(1);
}

/* Coerção: int/float interoperam; string não. */
static LAMO_UNUSED long long lamo_as_int(LamoValue value) {
    if (value.type == LAMO_VALUE_STRING) {
        lamo_runtime_type_error("expected int-compatible value, got string");
    }
    if (value.type == LAMO_VALUE_FLOAT) {
        return (long long)value.float_value;
    }
    return value.int_value;
}

static LAMO_UNUSED double lamo_as_float(LamoValue value) {
    if (value.type == LAMO_VALUE_STRING) {
        lamo_runtime_type_error("expected number, got string");
    }
    if (value.type == LAMO_VALUE_FLOAT) {
        return value.float_value;
    }
    return (double)value.int_value;
}

static LAMO_UNUSED const char* lamo_as_cstring(LamoValue value) {
    if (value.type != LAMO_VALUE_STRING) {
        lamo_runtime_type_error("expected string value");
    }
    return value.string_value ? value.string_value : "";
}

static LAMO_UNUSED char* lamo_value_to_owned_string(LamoValue value) {
    char buffer[64];
    if (value.type == LAMO_VALUE_STRING) {
        return lamo_heap_strdup(lamo_as_cstring(value));
    }
    if (value.type == LAMO_VALUE_FLOAT) {
        snprintf(buffer, sizeof(buffer), "%g", value.float_value);
        return lamo_heap_strdup(buffer);
    }
    if (value.type == LAMO_VALUE_BOOL) {
        return lamo_heap_strdup(value.int_value ? "true" : "false");
    }
    if (value.type == LAMO_VALUE_ARRAY || value.type == LAMO_VALUE_STRUCT) {
        /* Recursively render the array/struct into a heap string. We
         * build a temporary buffer, then strdup it. The capacity grows
         * as needed. */
        size_t cap = 64;
        size_t len = 0;
        char* out = (char*)malloc(cap);
        if (!out) return lamo_heap_strdup("");
        out[0] = '\0';
        #define LAMO_APPEND_STR(s) do { \
            size_t addlen = strlen(s); \
            if (len + addlen + 1 > cap) { \
                while (len + addlen + 1 > cap) cap *= 2; \
                char* grown = (char*)realloc(out, cap); \
                if (!grown) { free(out); return lamo_heap_strdup(""); } \
                out = grown; \
            } \
            memcpy(out + len, s, addlen); \
            len += addlen; \
            out[len] = '\0'; \
        } while (0)
        LAMO_APPEND_STR(value.type == LAMO_VALUE_STRUCT ? "{ " : "[");
        if (value.array_value) {
            long long i;
            for (i = 0; i < value.array_value->count; i++) {
                if (i > 0) LAMO_APPEND_STR(", ");
                char* elem = lamo_value_to_owned_string(value.array_value->items[i]);
                LAMO_APPEND_STR(elem);
                free(elem);
            }
        }
        LAMO_APPEND_STR(value.type == LAMO_VALUE_STRUCT ? " }" : "]");
        #undef LAMO_APPEND_STR
        return out;
    }
    snprintf(buffer, sizeof(buffer), "%lld", value.int_value);
    return lamo_heap_strdup(buffer);
}

static LAMO_UNUSED LamoValue lamo_concat_values(LamoValue left, LamoValue right) {
    char* left_text = lamo_value_to_owned_string(left);
    char* right_text = lamo_value_to_owned_string(right);
    size_t left_length = strlen(left_text);
    size_t right_length = strlen(right_text);
    char* combined = (char*)lamo_arena_alloc(left_length + right_length + 1);
    memcpy(combined, left_text, left_length);
    memcpy(combined + left_length, right_text, right_length + 1);
    free(left_text);
    free(right_text);
    return lamo_make_string(combined);
}

/*
 * Truthiness (DOCUMENTED — see README "Truthiness" section):
 *
 *   - int:     non-zero is true
 *   - float:   non-zero is true (0.0 is false)
 *   - bool:    the value itself
 *   - string:  non-empty is true ("" is false)
 *
 * This is Python-like truthiness, NOT Rust-like strict bool. `if (5)` and
 * `if ("abc")` are both valid and true. `if (0)` and `if ("")` are false.
 */
static LAMO_UNUSED int lamo_is_truthy(LamoValue value) {
    if (value.type == LAMO_VALUE_STRING) {
        return value.string_value && value.string_value[0] != '\0';
    }
    if (value.type == LAMO_VALUE_FLOAT) {
        return value.float_value != 0.0;
    }
    if (value.type == LAMO_VALUE_ARRAY) {
        /* Sprint 3: arrays are truthy if non-empty. */
        return value.array_value != NULL && value.array_value->count > 0;
    }
    if (value.type == LAMO_VALUE_STRUCT) {
        /* Phase 2: a struct value is always truthy (even an empty one
         * represents a constructed object). */
        return value.array_value != NULL;
    }
    return value.int_value != 0;
}

static LAMO_UNUSED void lamo_print_value(LamoValue value) {
    if (value.type == LAMO_VALUE_STRING) {
        printf("%s\n", value.string_value ? value.string_value : "");
    } else if (value.type == LAMO_VALUE_FLOAT) {
        printf("%g\n", value.float_value);
    } else if (value.type == LAMO_VALUE_ARRAY) {
        /* Sprint 3: print arrays in Python-like [a, b, c] form. Each
         * element is printed via its own lamo_value_to_owned_string
         * representation so strings show without quotes (matching
         * the existing `print` semantics for top-level values). */
        long long i;
        printf("[");
        if (value.array_value) {
            for (i = 0; i < value.array_value->count; i++) {
                if (i > 0) printf(", ");
                /* Reuse lamo_value_to_owned_string to format each element. */
                char* text = lamo_value_to_owned_string(value.array_value->items[i]);
                printf("%s", text);
                free(text);
            }
        }
        printf("]\n");
    } else if (value.type == LAMO_VALUE_STRUCT) {
        /* Phase 2: print structs in `S { v0, v1, ... }` form. We don't
         * know the struct's type name at runtime (that info lives in the
         * compiler), so we just print the values. This matches what
         * `print(player)` does for a Player{hp:10, name:"x"} - the user
         * typically prints specific fields (`print(player.hp)`) rather
         * than the whole struct. */
        long long i;
        printf("{ ");
        if (value.array_value) {
            for (i = 0; i < value.array_value->count; i++) {
                if (i > 0) printf(", ");
                char* text = lamo_value_to_owned_string(value.array_value->items[i]);
                printf("%s", text);
                free(text);
            }
        }
        printf(" }\n");
    } else {
        printf("%lld\n", value.int_value);
    }
}

/* ------------------------------------------------------------------ */
/* Sprint 3: Array runtime                                            */
/* ------------------------------------------------------------------ */

/* Allocate a new LamoArray with the given initial capacity. The struct
 * is registered in the arena; its `items` buffer is also arena-tracked
 * (so it survives until program exit). */
static LAMO_UNUSED LamoArray* lamo_array_alloc(long long initial_capacity) {
    LamoArray* array;
    if (initial_capacity < 4) initial_capacity = 4;
    array = (LamoArray*)lamo_arena_alloc(sizeof(LamoArray));
    array->items = (LamoValue*)lamo_arena_alloc(sizeof(LamoValue) * (size_t)initial_capacity);
    array->count = 0;
    array->capacity = initial_capacity;
    return array;
}

/* Build an array value from a list of LamoValues. Used by the codegen
 * for array literals. The values are copied into a new buffer. */
static LAMO_UNUSED LamoValue lamo_array_from_values(LamoValue* values, long long count) {
    long long i;
    LamoArray* array = lamo_array_alloc(count > 0 ? count : 4);
    for (i = 0; i < count; i++) {
        array->items[i] = values[i];
    }
    array->count = count;
    return lamo_make_array(array);
}

/* Get element at index. Negative indices count from the end (-1 is the
 * last element). Out-of-range indices abort with a clear runtime error. */
static LAMO_UNUSED LamoValue lamo_array_get(LamoValue array_val, long long index) {
    LamoArray* array;
    if (array_val.type != LAMO_VALUE_ARRAY) {
        lamo_runtime_type_error("expected array value for indexing");
    }
    array = array_val.array_value;
    if (!array) {
        lamo_runtime_type_error("indexed array is NULL (internal error)");
    }
    if (index < 0) index += array->count;  /* Python-like negative index */
    if (index < 0 || index >= array->count) {
        fprintf(stderr, "runtime error: array index %lld out of bounds (array length %lld)\n",
                index, array->count);
        exit(1);
    }
    return array->items[index];
}

/* Returns the length of an array. */
static LAMO_UNUSED LamoValue lamo_array_len(LamoValue array_val) {
    if (array_val.type != LAMO_VALUE_ARRAY) {
        lamo_runtime_type_error("expected array value for len()");
    }
    if (!array_val.array_value) {
        return lamo_make_int(0);
    }
    return lamo_make_int(array_val.array_value->count);
}

/* Push a value onto the end of the array. Grows the internal buffer if
 * needed via realloc (the new buffer is registered in the arena; the old
 * one is leaked until program exit, same as the existing string-arena
 * policy). Returns 0 on success. */
static LAMO_UNUSED LamoValue lamo_array_push(LamoValue array_val, LamoValue value) {
    LamoArray* array;
    if (array_val.type != LAMO_VALUE_ARRAY) {
        lamo_runtime_type_error("expected array value for push()");
    }
    array = array_val.array_value;
    if (!array) {
        lamo_runtime_type_error("push() target array is NULL (internal error)");
    }
    if (array->count == array->capacity) {
        long long new_cap = array->capacity * 2;
        LamoValue* new_items = (LamoValue*)lamo_arena_alloc(sizeof(LamoValue) * (size_t)new_cap);
        memcpy(new_items, array->items, sizeof(LamoValue) * (size_t)array->count);
        array->items = new_items;
        array->capacity = new_cap;
    }
    array->items[array->count++] = value;
    return lamo_make_int(0);
}

/* Pop the last element from the array and return it. Aborts if the
 * array is empty. */
static LAMO_UNUSED LamoValue lamo_array_pop(LamoValue array_val) {
    LamoArray* array;
    LamoValue popped;
    if (array_val.type != LAMO_VALUE_ARRAY) {
        lamo_runtime_type_error("expected array value for pop()");
    }
    array = array_val.array_value;
    if (!array || array->count == 0) {
        fprintf(stderr, "runtime error: pop() on empty array\n");
        exit(1);
    }
    popped = array->items[--array->count];
    return popped;
}

/* Phase 2: array index assignment — `arr[i] = value`.
 * Returns the assigned value (so it can be used in expressions, e.g.
 * `let old = (arr[0] = 42);` though that's not idiomatic). */
static LAMO_UNUSED LamoValue lamo_array_set(LamoValue array_val, long long index, LamoValue value) {
    LamoArray* array;
    if (array_val.type != LAMO_VALUE_ARRAY) {
        lamo_runtime_type_error("expected array value for index assignment");
    }
    array = array_val.array_value;
    if (!array) {
        lamo_runtime_type_error("index-assign target array is NULL (internal error)");
    }
    if (index < 0) index += array->count;
    if (index < 0 || index >= array->count) {
        fprintf(stderr, "runtime error: array index %lld out of bounds in assignment (array length %lld)\n",
                index, array->count);
        exit(1);
    }
    array->items[index] = value;
    return value;
}

/* Phase 2: struct helpers. Structs reuse LamoArray under the hood.
 *
 * lamo_struct_alloc(n) - create a struct value with n zero-initialized
 *   fields (each slot is lamo_make_int(0)).
 * lamo_struct_get(sval, i) - read field at index i (lamo_array_get works
 *   too, but this function emits a clearer error message).
 * lamo_struct_set(sval, i, value) - write field at index i. Returns the
 *   assigned value (so it can be used in expressions). */
static LAMO_UNUSED LamoValue lamo_struct_alloc(long long field_count) {
    long long i;
    LamoArray* array;
    if (field_count < 0) field_count = 0;
    array = lamo_array_alloc(field_count > 0 ? field_count : 4);
    for (i = 0; i < field_count; i++) {
        array->items[i] = lamo_make_int(0);
    }
    array->count = field_count;
    return lamo_make_struct(array);
}

static LAMO_UNUSED LamoValue lamo_struct_get(LamoValue struct_val, long long index) {
    LamoArray* array;
    if (struct_val.type != LAMO_VALUE_STRUCT) {
        lamo_runtime_type_error("expected struct value for field access");
    }
    array = struct_val.array_value;
    if (!array) {
        lamo_runtime_type_error("field access on NULL struct (internal error)");
    }
    if (index < 0 || index >= array->count) {
        fprintf(stderr, "runtime error: struct field index %lld out of bounds (field count %lld)\n",
                index, array->count);
        exit(1);
    }
    return array->items[index];
}

static LAMO_UNUSED LamoValue lamo_struct_set(LamoValue struct_val, long long index, LamoValue value) {
    LamoArray* array;
    if (struct_val.type != LAMO_VALUE_STRUCT) {
        lamo_runtime_type_error("expected struct value for field assignment");
    }
    array = struct_val.array_value;
    if (!array) {
        lamo_runtime_type_error("field-assign target struct is NULL (internal error)");
    }
    if (index < 0 || index >= array->count) {
        fprintf(stderr, "runtime error: struct field index %lld out of bounds in assignment (field count %lld)\n",
                index, array->count);
        exit(1);
    }
    array->items[index] = value;
    return value;
}

/* Operações aritméticas: se qualquer operando for float, resultado é float. */
static LAMO_UNUSED LamoValue lamo_add(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_STRING || right.type == LAMO_VALUE_STRING) {
        return lamo_concat_values(left, right);
    }
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_float(lamo_as_float(left) + lamo_as_float(right));
    }
    return lamo_make_int(lamo_as_int(left) + lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_sub(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_float(lamo_as_float(left) - lamo_as_float(right));
    }
    return lamo_make_int(lamo_as_int(left) - lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_mul(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_float(lamo_as_float(left) * lamo_as_float(right));
    }
    return lamo_make_int(lamo_as_int(left) * lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_div(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        double lhs = lamo_as_float(left);
        double rhs = lamo_as_float(right);
        if (rhs == 0.0) {
            fprintf(stderr, "runtime error: division by zero\n");
            exit(1);
        }
        return lamo_make_float(lhs / rhs);
    }
    {
        long long lhs = lamo_as_int(left);
        long long rhs = lamo_as_int(right);
        if (rhs == 0) {
            fprintf(stderr, "runtime error: division by zero\n");
            exit(1);
        }
        return lamo_make_int(lhs / rhs);
    }
}

static LAMO_UNUSED LamoValue lamo_mod(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        double lhs = lamo_as_float(left);
        double rhs = lamo_as_float(right);
        if (rhs == 0.0) {
            fprintf(stderr, "runtime error: modulo by zero\n");
            exit(1);
        }
        return lamo_make_float(fmod(lhs, rhs));
    }
    {
        long long lhs = lamo_as_int(left);
        long long rhs = lamo_as_int(right);
        if (rhs == 0) {
            fprintf(stderr, "runtime error: modulo by zero\n");
            exit(1);
        }
        return lamo_make_int(lhs % rhs);
    }
}

static LAMO_UNUSED LamoValue lamo_negate(LamoValue value) {
    if (value.type == LAMO_VALUE_FLOAT) return lamo_make_float(-value.float_value);
    return lamo_make_int(-lamo_as_int(value));
}

static LAMO_UNUSED LamoValue lamo_not(LamoValue value) {
    return lamo_make_bool(!lamo_is_truthy(value));
}

static LAMO_UNUSED LamoValue lamo_less(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_bool(lamo_as_float(left) < lamo_as_float(right));
    }
    return lamo_make_bool(lamo_as_int(left) < lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_greater(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_bool(lamo_as_float(left) > lamo_as_float(right));
    }
    return lamo_make_bool(lamo_as_int(left) > lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_less_equal(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_bool(lamo_as_float(left) <= lamo_as_float(right));
    }
    return lamo_make_bool(lamo_as_int(left) <= lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_greater_equal(LamoValue left, LamoValue right) {
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_bool(lamo_as_float(left) >= lamo_as_float(right));
    }
    return lamo_make_bool(lamo_as_int(left) >= lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_equal(LamoValue left, LamoValue right) {
    /* Phase 2: arrays and structs compare by identity (same pointer).
     * Deep equality would be expensive and surprising for mutable values. */
    if (left.type == LAMO_VALUE_ARRAY || left.type == LAMO_VALUE_STRUCT ||
        right.type == LAMO_VALUE_ARRAY || right.type == LAMO_VALUE_STRUCT) {
        if (left.type != right.type) return lamo_make_bool(0);
        return lamo_make_bool(left.array_value == right.array_value);
    }
    if (left.type == LAMO_VALUE_STRING || right.type == LAMO_VALUE_STRING) {
        if (left.type != LAMO_VALUE_STRING || right.type != LAMO_VALUE_STRING) {
            return lamo_make_bool(0);
        }
        return lamo_make_bool(strcmp(lamo_as_cstring(left), lamo_as_cstring(right)) == 0);
    }
    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {
        return lamo_make_bool(lamo_as_float(left) == lamo_as_float(right));
    }
    return lamo_make_bool(lamo_as_int(left) == lamo_as_int(right));
}

static LAMO_UNUSED LamoValue lamo_not_equal(LamoValue left, LamoValue right) {
    LamoValue result = lamo_equal(left, right);
    return lamo_make_bool(!lamo_is_truthy(result));
}

static LAMO_UNUSED LamoValue lamo_and(LamoValue left, LamoValue right) {
    return lamo_make_bool(lamo_is_truthy(left) && lamo_is_truthy(right));
}

static LAMO_UNUSED LamoValue lamo_or(LamoValue left, LamoValue right) {
    return lamo_make_bool(lamo_is_truthy(left) || lamo_is_truthy(right));
}

static LAMO_UNUSED void lamo_print_prompt(LamoValue prompt) {
    if (prompt.type == LAMO_VALUE_STRING) {
        printf("%s", lamo_as_cstring(prompt));
    } else if (prompt.type == LAMO_VALUE_FLOAT) {
        printf("%g", prompt.float_value);
    } else {
        printf("%lld", prompt.int_value);
    }
    fflush(stdout);
}

/* input(prompt) - reads an integer from stdin. Kept for compatibility with
 * existing programs. To read strings, use input_str(prompt). */
static LAMO_UNUSED LamoValue lamo_input_value(LamoValue prompt) {
    long long value;
    lamo_print_prompt(prompt);
    if (scanf("%lld", &value) != 1) {
        value = 0;
    }
    return lamo_make_int(value);
}

/* input_int(prompt) - explicit alias for input(), reads long long. */
static LAMO_UNUSED LamoValue lamo_input_int_value(LamoValue prompt) {
    long long value;
    lamo_print_prompt(prompt);
    if (scanf("%lld", &value) != 1) {
        value = 0;
    }
    return lamo_make_int(value);
}

/* input_str(prompt) - reads one line of text from stdin, without the trailing
 * newline. The returned string is allocated in the string arena (freed at
 * atexit). */
static LAMO_UNUSED LamoValue lamo_input_str_value(LamoValue prompt) {
    char buffer[1024];
    size_t length;
    char* owned;
    lamo_print_prompt(prompt);
    if (fgets(buffer, sizeof(buffer), stdin) == NULL) {
        buffer[0] = '\0';
    }
    length = strlen(buffer);
    while (length > 0 && (buffer[length-1] == '\n' || buffer[length-1] == '\r')) {
        buffer[--length] = '\0';
    }
    owned = lamo_arena_strdup(buffer);
    return lamo_make_string(owned);
}

static LAMO_UNUSED LamoValue lamo_isnumber_value(LamoValue value) {
    return lamo_make_bool(value.type == LAMO_VALUE_INT || value.type == LAMO_VALUE_FLOAT);
}

static LAMO_UNUSED LamoValue lamo_isstring_value(LamoValue value) {
    return lamo_make_bool(value.type == LAMO_VALUE_STRING);
}

static LAMO_UNUSED LamoValue lamo_abs_value(LamoValue value) {
    if (value.type == LAMO_VALUE_FLOAT) {
        double v = value.float_value;
        return lamo_make_float(v < 0 ? -v : v);
    }
    {
        long long raw = lamo_as_int(value);
        return lamo_make_int(raw < 0 ? -raw : raw);
    }
}

/* ------------------------------------------------------------------ */
/* 2. GUI runtime (only emitted when the program uses gui_* builtins) */
/* ------------------------------------------------------------------ */
#ifdef LAMO_NEEDS_GUI_RUNTIME

#ifdef _WIN32
#include <windows.h>

typedef struct {
    HWND hwnd;
    HDC back_dc;
    HBITMAP back_bitmap;
    HFONT font;
    int width;
    int height;
    int is_open;
} LamoGuiState;

static LamoGuiState lamo_gui = {0};
static int lamo_gui_registered = 0;

static LRESULT CALLBACK lamo_gui_window_proc(HWND hwnd, UINT message, WPARAM w_param, LPARAM l_param) {
    (void)l_param;
    switch (message) {
        case WM_CLOSE:
            lamo_gui.is_open = 0;
            DestroyWindow(hwnd);
            return 0;
        case WM_DESTROY:
            lamo_gui.is_open = 0;
            PostQuitMessage(0);
            return 0;
        default:
            return DefWindowProcA(hwnd, message, w_param, l_param);
    }
}

static void lamo_gui_process_messages(void) {
    MSG message;
    while (PeekMessageA(&message, NULL, 0, 0, PM_REMOVE)) {
        if (message.message == WM_QUIT) {
            lamo_gui.is_open = 0;
        }
        TranslateMessage(&message);
        DispatchMessageA(&message);
    }
}

static int lamo_gui_open(int width, int height, const char* title) {
    WNDCLASSA window_class;
    HDC window_dc;
    RECT rect;
    if (lamo_gui.is_open) { return 1; }
    if (!lamo_gui_registered) {
        ZeroMemory(&window_class, sizeof(window_class));
        window_class.lpfnWndProc = lamo_gui_window_proc;
        window_class.hInstance = GetModuleHandleA(NULL);
        window_class.lpszClassName = "LamoGuiWindow";
        window_class.hCursor = LoadCursor(NULL, IDC_ARROW);
        window_class.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
        if (!RegisterClassA(&window_class)) {
            DWORD error_code = GetLastError();
            if (error_code != ERROR_CLASS_ALREADY_EXISTS) {
                fprintf(stderr, "failed to register GUI window class (error %lu)\n", (unsigned long)error_code);
                return 0;
            }
        }
        lamo_gui_registered = 1;
    }
    lamo_gui.width = width;
    lamo_gui.height = height;
    rect.left = 0; rect.top = 0; rect.right = width; rect.bottom = height;
    AdjustWindowRect(&rect, WS_OVERLAPPEDWINDOW, 0);
    lamo_gui.hwnd = CreateWindowExA(0, "LamoGuiWindow", title, WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT, rect.right - rect.left, rect.bottom - rect.top,
        NULL, NULL, GetModuleHandleA(NULL), NULL);
    if (!lamo_gui.hwnd) { fprintf(stderr, "failed to create GUI window\n"); return 0; }
    ShowWindow(lamo_gui.hwnd, SW_SHOW);
    UpdateWindow(lamo_gui.hwnd);
    window_dc = GetDC(lamo_gui.hwnd);
    lamo_gui.back_dc = CreateCompatibleDC(window_dc);
    lamo_gui.back_bitmap = CreateCompatibleBitmap(window_dc, width, height);
    SelectObject(lamo_gui.back_dc, lamo_gui.back_bitmap);
    ReleaseDC(lamo_gui.hwnd, window_dc);
    SetBkMode(lamo_gui.back_dc, TRANSPARENT);
    lamo_gui.font = CreateFontA(24, 0, 0, 0, FW_NORMAL, 0, 0, 0, ANSI_CHARSET,
        OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY,
        DEFAULT_PITCH | FF_DONTCARE, "Segoe UI");
    if (lamo_gui.font) { SelectObject(lamo_gui.back_dc, lamo_gui.font); }
    lamo_gui.is_open = 1;
    return 1;
}

static int lamo_gui_should_close(void) {
    lamo_gui_process_messages();
    return lamo_gui.is_open ? 0 : 1;
}

static void lamo_gui_begin_frame(int r, int g, int b) {
    RECT rect; HBRUSH brush;
    if (!lamo_gui.is_open) return;
    rect.left = 0; rect.top = 0; rect.right = lamo_gui.width; rect.bottom = lamo_gui.height;
    brush = CreateSolidBrush(RGB(r, g, b));
    FillRect(lamo_gui.back_dc, &rect, brush);
    DeleteObject(brush);
}

static void lamo_gui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {
    RECT rect; HBRUSH brush;
    if (!lamo_gui.is_open) return;
    rect.left = x; rect.top = y; rect.right = x + width; rect.bottom = y + height;
    brush = CreateSolidBrush(RGB(r, g, b));
    FillRect(lamo_gui.back_dc, &rect, brush);
    DeleteObject(brush);
}

static void lamo_gui_draw_text(const char* text, int x, int y, int r, int g, int b) {
    if (!lamo_gui.is_open) return;
    SetTextColor(lamo_gui.back_dc, RGB(r, g, b));
    TextOutA(lamo_gui.back_dc, x, y, text, (int)strlen(text));
}

static void lamo_gui_end_frame(void) {
    HDC window_dc;
    if (!lamo_gui.is_open) return;
    window_dc = GetDC(lamo_gui.hwnd);
    BitBlt(window_dc, 0, 0, lamo_gui.width, lamo_gui.height, lamo_gui.back_dc, 0, 0, SRCCOPY);
    ReleaseDC(lamo_gui.hwnd, window_dc);
}

static void lamo_gui_close(void) {
    if (lamo_gui.font) { DeleteObject(lamo_gui.font); lamo_gui.font = NULL; }
    if (lamo_gui.back_bitmap) { DeleteObject(lamo_gui.back_bitmap); lamo_gui.back_bitmap = NULL; }
    if (lamo_gui.back_dc) { DeleteDC(lamo_gui.back_dc); lamo_gui.back_dc = NULL; }
    if (lamo_gui.hwnd) { DestroyWindow(lamo_gui.hwnd); lamo_gui.hwnd = NULL; }
    lamo_gui.is_open = 0;
}
#elif defined(__unix__) || defined(__unix) || defined(__linux__) || defined(__APPLE__)
/* Backend X11 for Linux/Mac. C and Xlib are trivial to link (-lX11). */
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xos.h>

typedef struct {
    Display* display;
    Window window;
    GC gc;
    Pixmap back_pixmap;
    XFontStruct* font;
    int width;
    int height;
    int is_open;
    Atom wm_delete;
} LamoGuiState;

static LamoGuiState lamo_gui = {0};

static int lamo_gui_open(int width, int height, const char* title) {
    int screen;
    if (lamo_gui.is_open) { return 1; }
    lamo_gui.display = XOpenDisplay(NULL);
    if (!lamo_gui.display) {
        fprintf(stderr, "failed to open X11 display\n");
        return 0;
    }
    screen = DefaultScreen(lamo_gui.display);
    lamo_gui.width = width;
    lamo_gui.height = height;
    lamo_gui.window = XCreateSimpleWindow(lamo_gui.display,
        RootWindow(lamo_gui.display, screen),
        0, 0, width, height, 1,
        BlackPixel(lamo_gui.display, screen),
        WhitePixel(lamo_gui.display, screen));
    XSelectInput(lamo_gui.display, lamo_gui.window,
        ExposureMask | StructureNotifyMask);
    XStoreName(lamo_gui.display, lamo_gui.window, title ? title : "Lamo");
    lamo_gui.wm_delete = XInternAtom(lamo_gui.display, "WM_DELETE_WINDOW", False);
    XSetWMProtocols(lamo_gui.display, lamo_gui.window, &lamo_gui.wm_delete, 1);
    lamo_gui.gc = XCreateGC(lamo_gui.display, lamo_gui.window, 0, NULL);
    lamo_gui.back_pixmap = XCreatePixmap(lamo_gui.display, lamo_gui.window,
        width, height, DefaultDepth(lamo_gui.display, screen));
    lamo_gui.font = XLoadQueryFont(lamo_gui.display, "fixed");
    if (lamo_gui.font) { XSetFont(lamo_gui.display, lamo_gui.gc, lamo_gui.font->fid); }
    XMapWindow(lamo_gui.display, lamo_gui.window);
    XFlush(lamo_gui.display);
    lamo_gui.is_open = 1;
    return 1;
}

static void lamo_gui_process_messages(void) {
    XEvent event;
    while (XPending(lamo_gui.display) > 0) {
        XNextEvent(lamo_gui.display, &event);
        if (event.type == ClientMessage) {
            if ((Atom)event.xclient.data.l[0] == lamo_gui.wm_delete) {
                lamo_gui.is_open = 0;
            }
        }
    }
}

static int lamo_gui_should_close(void) {
    if (!lamo_gui.display) return 1;
    lamo_gui_process_messages();
    return lamo_gui.is_open ? 0 : 1;
}

static void lamo_gui_begin_frame(int r, int g, int b) {
    XColor color;
    if (!lamo_gui.is_open) return;
    color.red = (unsigned short)(r * 257);
    color.green = (unsigned short)(g * 257);
    color.blue = (unsigned short)(b * 257);
    color.flags = DoRed | DoGreen | DoBlue;
    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);
    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);
    XFillRectangle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,
        0, 0, lamo_gui.width, lamo_gui.height);
}

static void lamo_gui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {
    XColor color;
    if (!lamo_gui.is_open) return;
    color.red = (unsigned short)(r * 257);
    color.green = (unsigned short)(g * 257);
    color.blue = (unsigned short)(b * 257);
    color.flags = DoRed | DoGreen | DoBlue;
    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);
    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);
    XFillRectangle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,
        x, y, width, height);
}

static void lamo_gui_draw_text(const char* text, int x, int y, int r, int g, int b) {
    XColor color;
    if (!lamo_gui.is_open) return;
    color.red = (unsigned short)(r * 257);
    color.green = (unsigned short)(g * 257);
    color.blue = (unsigned short)(b * 257);
    color.flags = DoRed | DoGreen | DoBlue;
    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.display, 0), &color);
    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);
    XDrawString(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,
        x, y + (lamo_gui.font ? lamo_gui.font->ascent : 12),
        text ? text : "", text ? (int)strlen(text) : 0);
}

static void lamo_gui_end_frame(void) {
    if (!lamo_gui.is_open) return;
    XCopyArea(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.window, lamo_gui.gc,
        0, 0, lamo_gui.width, lamo_gui.height, 0, 0);
    XFlush(lamo_gui.display);
}

static void lamo_gui_close(void) {
    if (lamo_gui.font) { XFreeFont(lamo_gui.display, lamo_gui.font); lamo_gui.font = NULL; }
    if (lamo_gui.back_pixmap) { XFreePixmap(lamo_gui.display, lamo_gui.back_pixmap); lamo_gui.back_pixmap = 0; }
    if (lamo_gui.gc) { XFreeGC(lamo_gui.display, lamo_gui.gc); lamo_gui.gc = NULL; }
    if (lamo_gui.window) { XDestroyWindow(lamo_gui.display, lamo_gui.window); lamo_gui.window = 0; }
    if (lamo_gui.display) { XCloseDisplay(lamo_gui.display); lamo_gui.display = NULL; }
    lamo_gui.is_open = 0;
}
#else
static int lamo_gui_open(int width, int height, const char* title) {
    (void)width; (void)height; (void)title;
    fprintf(stderr, "GUI builtins are not supported on this platform.\n");
    return 0;
}
static int lamo_gui_should_close(void) { return 1; }
static void lamo_gui_begin_frame(int r, int g, int b) { (void)r; (void)g; (void)b; }
static void lamo_gui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {
    (void)x; (void)y; (void)width; (void)height; (void)r; (void)g; (void)b;
}
static void lamo_gui_draw_text(const char* text, int x, int y, int r, int g, int b) {
    (void)text; (void)x; (void)y; (void)r; (void)g; (void)b;
}
static void lamo_gui_end_frame(void) {}
static void lamo_gui_close(void) {}
#endif

#endif /* LAMO_NEEDS_GUI_RUNTIME */

/* ------------------------------------------------------------------ */
/* 3. HTTP runtime (only emitted when the program uses http_* builtins) */
/* ------------------------------------------------------------------ */
#ifdef LAMO_NEEDS_HTTP_RUNTIME

#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
typedef SOCKET lamo_socket_t;
#define LAMO_INVALID_SOCKET INVALID_SOCKET
#define lamo_close_socket closesocket
#else
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
typedef int lamo_socket_t;
#define LAMO_INVALID_SOCKET (-1)
#define lamo_close_socket close
#endif

typedef struct LamoHttpRoute {
    char* path;
    char* body;
    struct LamoHttpRoute* next;
} LamoHttpRoute;

static LamoHttpRoute* lamo_http_routes = NULL;
static int lamo_http_runtime_initialized = 0;

static int lamo_http_init_runtime(void) {
#ifdef _WIN32
    WSADATA wsa_data;
    if (!lamo_http_runtime_initialized) {
        if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {
            fprintf(stderr, "failed to initialize Winsock\n");
            return 0;
        }
        lamo_http_runtime_initialized = 1;
    }
#else
    lamo_http_runtime_initialized = 1;
#endif
    return 1;
}

static void lamo_http_add_route(const char* path, const char* body) {
    LamoHttpRoute* route;
    if (!lamo_http_init_runtime()) { return; }
    route = malloc(sizeof(LamoHttpRoute));
    if (!route) { fprintf(stderr, "failed to allocate HTTP route\n"); exit(1); }
    route->path = lamo_heap_strdup(path);
    route->body = lamo_heap_strdup(body);
    route->next = lamo_http_routes;
    lamo_http_routes = route;
}

static const LamoHttpRoute* lamo_http_find_route(const char* path) {
    LamoHttpRoute* current = lamo_http_routes;
    while (current) {
        if (strcmp(current->path, path) == 0) { return current; }
        current = current->next;
    }
    return NULL;
}

static int lamo_http_send_all(lamo_socket_t socket_fd, const char* data, int total_length) {
    int sent = 0;
    while (sent < total_length) {
        int chunk = send(socket_fd, data + sent, total_length - sent, 0);
        if (chunk <= 0) { return 0; }
        sent += chunk;
    }
    return 1;
}

static int lamo_http_send_response(lamo_socket_t client_socket, int status_code, const char* body) {
    char header[512];
    const char* reason = status_code == 200 ? "OK" : "Not Found";
    int body_length = (int)strlen(body);
    int header_length = snprintf(header, sizeof(header),
        "HTTP/1.1 %d %s\r\n"
        "Content-Type: text/plain; charset=utf-8\r\n"
        "Content-Length: %d\r\n"
        "Connection: close\r\n\r\n",
        status_code, reason, body_length);
    if (header_length < 0 || !lamo_http_send_all(client_socket, header, header_length)) {
        return 0;
    }
    return lamo_http_send_all(client_socket, body, body_length);
}

static void lamo_http_handle_client(lamo_socket_t client_socket) {
    char request[2048];
    char method[16];
    char path[1024];
    int received = recv(client_socket, request, (int)sizeof(request) - 1, 0);
    if (received <= 0) { return; }
    request[received] = '\0';
    method[0] = '\0';
    path[0] = '\0';
    if (sscanf(request, "%15s %1023s", method, path) == 2) {
        const LamoHttpRoute* route = lamo_http_find_route(path);
        if (route) {
            lamo_http_send_response(client_socket, 200, route->body);
            return;
        }
    }
    lamo_http_send_response(client_socket, 404, "not found");
}

static int lamo_http_run_server(int port, int serve_once) {
    lamo_socket_t server_socket;
    struct sockaddr_in address;
    int opt_value = 1;
    if (!lamo_http_init_runtime()) { return 0; }
    server_socket = socket(AF_INET, SOCK_STREAM, 0);
    if (server_socket == LAMO_INVALID_SOCKET) {
        fprintf(stderr, "failed to create HTTP socket\n");
        return 0;
    }
    setsockopt(server_socket, SOL_SOCKET, SO_REUSEADDR, (const char*)&opt_value, sizeof(opt_value));
    memset(&address, 0, sizeof(address));
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    address.sin_port = htons((unsigned short)port);
    if (bind(server_socket, (struct sockaddr*)&address, sizeof(address)) != 0) {
        fprintf(stderr, "failed to bind HTTP server on port %d\n", port);
        lamo_close_socket(server_socket);
        return 0;
    }
    if (listen(server_socket, 8) != 0) {
        fprintf(stderr, "failed to listen on HTTP server port %d\n", port);
        lamo_close_socket(server_socket);
        return 0;
    }
    while (1) {
        lamo_socket_t client_socket = accept(server_socket, NULL, NULL);
        if (client_socket == LAMO_INVALID_SOCKET) { break; }
        lamo_http_handle_client(client_socket);
        lamo_close_socket(client_socket);
        if (serve_once) { break; }
    }
    lamo_close_socket(server_socket);
    return 1;
}

#endif /* LAMO_NEEDS_HTTP_RUNTIME */

#endif /* LAMO_RUNTIME_H */
