/*
 * lamo_runtime_data.c - AUTO-GENERATED. Do not edit by hand.
 *
 * Regenerate with: python3 scripts/embed_runtime.py
 *
 * Contains the Lamo runtime (from lamo_runtime.h) as an escaped C
 * string. The codegen emits this verbatim at the top of every
 * generated .c program, replacing ~600 lines of fprintf() calls.
 */

#include "lamo_runtime_data.h"

const char lamo_runtime_source[] =
    "#ifndef LAMO_RUNTIME_H\n#define LAMO_RUNTIME_H\n\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n#if de"
    "fined(__GNUC__) || defined(__clang__)\n#define LAMO_UNUSED __attribute__((unused))\n#else\n#define LAMO_UNUSED\n#endif\n"
    "\n/* ------------------------------------------------------------------ */\n/* 1. Value runtime (always present)        "
    "                          */\n/* ------------------------------------------------------------------ */\n\ntypedef enum {"
    "\n    LAMO_VALUE_INT,\n    LAMO_VALUE_FLOAT,\n    LAMO_VALUE_STRING,\n    LAMO_VALUE_BOOL\n} LamoValueType;\n\ntypedef s"
    "truct {\n    LamoValueType type;\n    long long int_value;\n    double float_value;\n    const char* string_value;\n} La"
    "moValue;\n\nstatic LAMO_UNUSED LamoValue lamo_make_int(long long value) {\n    LamoValue result;\n    result.type = LAMO"
    "_VALUE_INT;\n    result.int_value = value;\n    result.float_value = 0.0;\n    result.string_value = NULL;\n    return r"
    "esult;\n}\n\nstatic LAMO_UNUSED LamoValue lamo_make_float(double value) {\n    LamoValue result;\n    result.type = LAMO"
    "_VALUE_FLOAT;\n    result.int_value = 0;\n    result.float_value = value;\n    result.string_value = NULL;\n    return r"
    "esult;\n}\n\nstatic LAMO_UNUSED LamoValue lamo_make_bool(int value) {\n    LamoValue result;\n    result.type = LAMO_VAL"
    "UE_BOOL;\n    result.int_value = value ? 1 : 0;\n    result.float_value = 0.0;\n    result.string_value = NULL;\n    ret"
    "urn result;\n}\n\nstatic LAMO_UNUSED LamoValue lamo_make_string(const char* value) {\n    LamoValue result;\n    result."
    "type = LAMO_VALUE_STRING;\n    result.int_value = 0;\n    result.float_value = 0.0;\n    result.string_value = value ? v"
    "alue : \"\";\n    return result;\n}\n\n/* ---- String arena --------------------------------------------------\n * The L"
    "amo runtime has no GC and no per-LamoValue ownership tracking.\n * Strings allocated dynamically (concatenation, input_s"
    "tr, ...) are\n * registered in this arena and freed all at once on program exit via\n * atexit(). This fixes the classic"
    " leak in loops that concatenate:\n * before, each `s = s + \"x\"` leaked the previous buffer; now every\n * buffer is tr"
    "acked and freed on shutdown.\n *\n * Known limitation: long-running programs (e.g. HTTP servers) see the\n * arena grow "
    "while they run. This is acceptable for an educational\n * prototype and is documented in the README.\n */\nstatic char**"
    " lamo_string_arena = NULL;\nstatic size_t lamo_string_arena_count = 0;\nstatic size_t lamo_string_arena_capacity = 0;\n"
    "\nstatic LAMO_UNUSED char* lamo_arena_alloc(size_t length) {\n    char* block;\n    if (lamo_string_arena_count == lamo_"
    "string_arena_capacity) {\n        size_t new_cap = lamo_string_arena_capacity ? lamo_string_arena_capacity * 2 : 16;\n  "
    "      char** new_arena = realloc(lamo_string_arena, sizeof(char*) * new_cap);\n        if (!new_arena) { fprintf(stderr,"
    " \"runtime error: string arena exhausted\\n\"); exit(1); }\n        lamo_string_arena = new_arena;\n        lamo_string_"
    "arena_capacity = new_cap;\n    }\n    block = malloc(length);\n    if (!block) { fprintf(stderr, \"runtime error: failed"
    " to allocate string\\n\"); exit(1); }\n    lamo_string_arena[lamo_string_arena_count++] = block;\n    return block;\n}\n"
    "\nstatic LAMO_UNUSED char* lamo_arena_strdup(const char* value) {\n    size_t length;\n    char* copy;\n    if (!value) "
    "{ value = \"\"; }\n    length = strlen(value);\n    copy = lamo_arena_alloc(length + 1);\n    memcpy(copy, value, length"
    " + 1);\n    return copy;\n}\n\nstatic LAMO_UNUSED void lamo_arena_free_all(void) {\n    size_t i;\n    for (i = 0; i < l"
    "amo_string_arena_count; i++) {\n        free(lamo_string_arena[i]);\n    }\n    free(lamo_string_arena);\n    lamo_strin"
    "g_arena = NULL;\n    lamo_string_arena_count = 0;\n    lamo_string_arena_capacity = 0;\n}\n\nstatic LAMO_UNUSED char* la"
    "mo_heap_strdup(const char* value) {\n    size_t length;\n    char* copy;\n    if (!value) { value = \"\"; }\n    length "
    "= strlen(value);\n    copy = malloc(length + 1);\n    if (!copy) {\n        fprintf(stderr, \"runtime error: failed to a"
    "llocate string\\n\");\n        exit(1);\n    }\n    memcpy(copy, value, length + 1);\n    return copy;\n}\n\nstatic LAMO"
    "_UNUSED void lamo_runtime_type_error(const char* message) {\n    fprintf(stderr, \"runtime error: %s\\n\", message);\n  "
    "  exit(1);\n}\n\n/* Coer\347\343o: int/float interoperam; string n\343o. */\nstatic LAMO_UNUSED long long lamo_as_int(La"
    "moValue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        lamo_runtime_type_error(\"expected int-compatible "
    "value, got string\");\n    }\n    if (value.type == LAMO_VALUE_FLOAT) {\n        return (long long)value.float_value;\n "
    "   }\n    return value.int_value;\n}\n\nstatic LAMO_UNUSED double lamo_as_float(LamoValue value) {\n    if (value.type ="
    "= LAMO_VALUE_STRING) {\n        lamo_runtime_type_error(\"expected number, got string\");\n    }\n    if (value.type == "
    "LAMO_VALUE_FLOAT) {\n        return value.float_value;\n    }\n    return (double)value.int_value;\n}\n\nstatic LAMO_UNU"
    "SED const char* lamo_as_cstring(LamoValue value) {\n    if (value.type != LAMO_VALUE_STRING) {\n        lamo_runtime_typ"
    "e_error(\"expected string value\");\n    }\n    return value.string_value ? value.string_value : \"\";\n}\n\nstatic LAMO"
    "_UNUSED char* lamo_value_to_owned_string(LamoValue value) {\n    char buffer[64];\n    if (value.type == LAMO_VALUE_STRI"
    "NG) {\n        return lamo_heap_strdup(lamo_as_cstring(value));\n    }\n    if (value.type == LAMO_VALUE_FLOAT) {\n     "
    "   snprintf(buffer, sizeof(buffer), \"%g\", value.float_value);\n        return lamo_heap_strdup(buffer);\n    }\n    sn"
    "printf(buffer, sizeof(buffer), \"%lld\", value.int_value);\n    return lamo_heap_strdup(buffer);\n}\n\nstatic LAMO_UNUSE"
    "D LamoValue lamo_concat_values(LamoValue left, LamoValue right) {\n    char* left_text = lamo_value_to_owned_string(left"
    ");\n    char* right_text = lamo_value_to_owned_string(right);\n    size_t left_length = strlen(left_text);\n    size_t r"
    "ight_length = strlen(right_text);\n    char* combined = lamo_arena_alloc(left_length + right_length + 1);\n    memcpy(co"
    "mbined, left_text, left_length);\n    memcpy(combined + left_length, right_text, right_length + 1);\n    free(left_text)"
    ";\n    free(right_text);\n    return lamo_make_string(combined);\n}\n\n/*\n * Truthiness (DOCUMENTED \20024 see README "
    "\"Truthiness\" section):\n *\n *   - int:     non-zero is true\n *   - float:   non-zero is true (0.0 is false)\n *   - "
    "bool:    the value itself\n *   - string:  non-empty is true (\"\" is false)\n *\n * This is Python-like truthiness, NOT"
    " Rust-like strict bool. `if (5)` and\n * `if (\"abc\")` are both valid and true. `if (0)` and `if (\"\")` are false.\n *"
    "/\nstatic LAMO_UNUSED int lamo_is_truthy(LamoValue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        return "
    "value.string_value && value.string_value[0] != '\\0';\n    }\n    if (value.type == LAMO_VALUE_FLOAT) {\n        return "
    "value.float_value != 0.0;\n    }\n    return value.int_value != 0;\n}\n\nstatic LAMO_UNUSED void lamo_print_value(LamoVa"
    "lue value) {\n    if (value.type == LAMO_VALUE_STRING) {\n        printf(\"%s\\n\", value.string_value ? value.string_va"
    "lue : \"\");\n    } else if (value.type == LAMO_VALUE_FLOAT) {\n        printf(\"%g\\n\", value.float_value);\n    } els"
    "e {\n        printf(\"%lld\\n\", value.int_value);\n    }\n}\n\n/* Opera\347\365es aritm\351ticas: se qualquer operando "
    "for float, resultado \351 float. */\nstatic LAMO_UNUSED LamoValue lamo_add(LamoValue left, LamoValue right) {\n    if (l"
    "eft.type == LAMO_VALUE_STRING || right.type == LAMO_VALUE_STRING) {\n        return lamo_concat_values(left, right);\n  "
    "  }\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_float(lamo_as_"
    "float(left) + lamo_as_float(right));\n    }\n    return lamo_make_int(lamo_as_int(left) + lamo_as_int(right));\n}\n\nsta"
    "tic LAMO_UNUSED LamoValue lamo_sub(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.ty"
    "pe == LAMO_VALUE_FLOAT) {\n        return lamo_make_float(lamo_as_float(left) - lamo_as_float(right));\n    }\n    retur"
    "n lamo_make_int(lamo_as_int(left) - lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_mul(LamoValue left, Lam"
    "oValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_fl"
    "oat(lamo_as_float(left) * lamo_as_float(right));\n    }\n    return lamo_make_int(lamo_as_int(left) * lamo_as_int(right)"
    ");\n}\n\nstatic LAMO_UNUSED LamoValue lamo_div(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT"
    " || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_float(lamo_as_float(left) / lamo_as_float(right));\n    "
    "}\n    return lamo_make_int(lamo_as_int(left) / lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_mod(LamoVal"
    "ue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return "
    "lamo_make_float((double)((long long)lamo_as_float(left) % (long long)lamo_as_float(right)));\n    }\n    return lamo_mak"
    "e_int(lamo_as_int(left) % lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_negate(LamoValue value) {\n    if"
    " (value.type == LAMO_VALUE_FLOAT) return lamo_make_float(-value.float_value);\n    return lamo_make_int(-lamo_as_int(val"
    "ue));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_not(LamoValue value) {\n    return lamo_make_bool(!lamo_is_truthy(value));"
    "\n}\n\nstatic LAMO_UNUSED LamoValue lamo_less(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT "
    "|| right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) < lamo_as_float(right));\n    }"
    "\n    return lamo_make_bool(lamo_as_int(left) < lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_greater(Lam"
    "oValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        ret"
    "urn lamo_make_bool(lamo_as_float(left) > lamo_as_float(right));\n    }\n    return lamo_make_bool(lamo_as_int(left) > la"
    "mo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_less_equal(LamoValue left, LamoValue right) {\n    if (left.t"
    "ype == LAMO_VALUE_FLOAT || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) <= lamo_"
    "as_float(right));\n    }\n    return lamo_make_bool(lamo_as_int(left) <= lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED L"
    "amoValue lamo_greater_equal(LamoValue left, LamoValue right) {\n    if (left.type == LAMO_VALUE_FLOAT || right.type == L"
    "AMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) >= lamo_as_float(right));\n    }\n    return lamo_"
    "make_bool(lamo_as_int(left) >= lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_equal(LamoValue left, LamoVa"
    "lue right) {\n    if (left.type == LAMO_VALUE_STRING || right.type == LAMO_VALUE_STRING) {\n        if (left.type != LAM"
    "O_VALUE_STRING || right.type != LAMO_VALUE_STRING) {\n            return lamo_make_bool(0);\n        }\n        return l"
    "amo_make_bool(strcmp(lamo_as_cstring(left), lamo_as_cstring(right)) == 0);\n    }\n    if (left.type == LAMO_VALUE_FLOAT"
    " || right.type == LAMO_VALUE_FLOAT) {\n        return lamo_make_bool(lamo_as_float(left) == lamo_as_float(right));\n    "
    "}\n    return lamo_make_bool(lamo_as_int(left) == lamo_as_int(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_not_equal"
    "(LamoValue left, LamoValue right) {\n    LamoValue result = lamo_equal(left, right);\n    return lamo_make_bool(!lamo_is"
    "_truthy(result));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_and(LamoValue left, LamoValue right) {\n    return lamo_make_b"
    "ool(lamo_is_truthy(left) && lamo_is_truthy(right));\n}\n\nstatic LAMO_UNUSED LamoValue lamo_or(LamoValue left, LamoValue"
    " right) {\n    return lamo_make_bool(lamo_is_truthy(left) || lamo_is_truthy(right));\n}\n\nstatic LAMO_UNUSED void lamo_"
    "print_prompt(LamoValue prompt) {\n    if (prompt.type == LAMO_VALUE_STRING) {\n        printf(\"%s\", lamo_as_cstring(pr"
    "ompt));\n    } else if (prompt.type == LAMO_VALUE_FLOAT) {\n        printf(\"%g\", prompt.float_value);\n    } else {\n "
    "       printf(\"%lld\", prompt.int_value);\n    }\n    fflush(stdout);\n}\n\n/* input(prompt) - reads an integer from st"
    "din. Kept for compatibility with\n * existing programs. To read strings, use input_str(prompt). */\nstatic LAMO_UNUSED L"
    "amoValue lamo_input_value(LamoValue prompt) {\n    long long value;\n    lamo_print_prompt(prompt);\n    if (scanf(\"%ll"
    "d\", &value) != 1) {\n        value = 0;\n    }\n    return lamo_make_int(value);\n}\n\n/* input_int(prompt) - explicit "
    "alias for input(), reads long long. */\nstatic LAMO_UNUSED LamoValue lamo_input_int_value(LamoValue prompt) {\n    long "
    "long value;\n    lamo_print_prompt(prompt);\n    if (scanf(\"%lld\", &value) != 1) {\n        value = 0;\n    }\n    ret"
    "urn lamo_make_int(value);\n}\n\n/* input_str(prompt) - reads one line of text from stdin, without the trailing\n * newli"
    "ne. The returned string is allocated in the string arena (freed at\n * atexit). */\nstatic LAMO_UNUSED LamoValue lamo_in"
    "put_str_value(LamoValue prompt) {\n    char buffer[1024];\n    size_t length;\n    char* owned;\n    lamo_print_prompt(p"
    "rompt);\n    if (fgets(buffer, sizeof(buffer), stdin) == NULL) {\n        buffer[0] = '\\0';\n    }\n    length = strlen"
    "(buffer);\n    while (length > 0 && (buffer[length-1] == '\\n' || buffer[length-1] == '\\r')) {\n        buffer[--length"
    "] = '\\0';\n    }\n    owned = lamo_arena_strdup(buffer);\n    return lamo_make_string(owned);\n}\n\nstatic LAMO_UNUSED "
    "LamoValue lamo_isnumber_value(LamoValue value) {\n    return lamo_make_bool(value.type == LAMO_VALUE_INT || value.type ="
    "= LAMO_VALUE_FLOAT);\n}\n\nstatic LAMO_UNUSED LamoValue lamo_isstring_value(LamoValue value) {\n    return lamo_make_boo"
    "l(value.type == LAMO_VALUE_STRING);\n}\n\nstatic LAMO_UNUSED LamoValue lamo_abs_value(LamoValue value) {\n    if (value."
    "type == LAMO_VALUE_FLOAT) {\n        double v = value.float_value;\n        return lamo_make_float(v < 0 ? -v : v);\n   "
    " }\n    {\n        long long raw = lamo_as_int(value);\n        return lamo_make_int(raw < 0 ? -raw : raw);\n    }\n}\n"
    "\n/* ------------------------------------------------------------------ */\n/* 2. GUI runtime (only emitted when the pro"
    "gram uses gui_* builtins) */\n/* ------------------------------------------------------------------ */\n#ifdef LAMO_NEED"
    "S_GUI_RUNTIME\n\n#ifdef _WIN32\n#include <windows.h>\n\ntypedef struct {\n    HWND hwnd;\n    HDC back_dc;\n    HBITMAP "
    "back_bitmap;\n    HFONT font;\n    int width;\n    int height;\n    int is_open;\n} LamoGuiState;\n\nstatic LamoGuiState"
    " lamo_gui = {0};\nstatic int lamo_gui_registered = 0;\n\nstatic LRESULT CALLBACK lamo_gui_window_proc(HWND hwnd, UINT me"
    "ssage, WPARAM w_param, LPARAM l_param) {\n    (void)l_param;\n    switch (message) {\n        case WM_CLOSE:\n          "
    "  lamo_gui.is_open = 0;\n            DestroyWindow(hwnd);\n            return 0;\n        case WM_DESTROY:\n            "
    "lamo_gui.is_open = 0;\n            PostQuitMessage(0);\n            return 0;\n        default:\n            return DefW"
    "indowProcA(hwnd, message, w_param, l_param);\n    }\n}\n\nstatic void lamo_gui_process_messages(void) {\n    MSG message"
    ";\n    while (PeekMessageA(&message, NULL, 0, 0, PM_REMOVE)) {\n        if (message.message == WM_QUIT) {\n            l"
    "amo_gui.is_open = 0;\n        }\n        TranslateMessage(&message);\n        DispatchMessageA(&message);\n    }\n}\n\ns"
    "tatic int lamo_gui_open(int width, int height, const char* title) {\n    WNDCLASSA window_class;\n    HDC window_dc;\n  "
    "  RECT rect;\n    if (lamo_gui.is_open) { return 1; }\n    if (!lamo_gui_registered) {\n        ZeroMemory(&window_class"
    ", sizeof(window_class));\n        window_class.lpfnWndProc = lamo_gui_window_proc;\n        window_class.hInstance = Get"
    "ModuleHandleA(NULL);\n        window_class.lpszClassName = \"LamoGuiWindow\";\n        window_class.hCursor = LoadCursor"
    "(NULL, IDC_ARROW);\n        window_class.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);\n        if (!RegisterClassA(&windo"
    "w_class)) {\n            DWORD error_code = GetLastError();\n            if (error_code != ERROR_CLASS_ALREADY_EXISTS) {"
    "\n                fprintf(stderr, \"failed to register GUI window class (error %lu)\\n\", (unsigned long)error_code);\n "
    "               return 0;\n            }\n        }\n        lamo_gui_registered = 1;\n    }\n    lamo_gui.width = width;"
    "\n    lamo_gui.height = height;\n    rect.left = 0; rect.top = 0; rect.right = width; rect.bottom = height;\n    AdjustW"
    "indowRect(&rect, WS_OVERLAPPEDWINDOW, 0);\n    lamo_gui.hwnd = CreateWindowExA(0, \"LamoGuiWindow\", title, WS_OVERLAPPE"
    "DWINDOW,\n        CW_USEDEFAULT, CW_USEDEFAULT, rect.right - rect.left, rect.bottom - rect.top,\n        NULL, NULL, Get"
    "ModuleHandleA(NULL), NULL);\n    if (!lamo_gui.hwnd) { fprintf(stderr, \"failed to create GUI window\\n\"); return 0; }"
    "\n    ShowWindow(lamo_gui.hwnd, SW_SHOW);\n    UpdateWindow(lamo_gui.hwnd);\n    window_dc = GetDC(lamo_gui.hwnd);\n    "
    "lamo_gui.back_dc = CreateCompatibleDC(window_dc);\n    lamo_gui.back_bitmap = CreateCompatibleBitmap(window_dc, width, h"
    "eight);\n    SelectObject(lamo_gui.back_dc, lamo_gui.back_bitmap);\n    ReleaseDC(lamo_gui.hwnd, window_dc);\n    SetBkM"
    "ode(lamo_gui.back_dc, TRANSPARENT);\n    lamo_gui.font = CreateFontA(24, 0, 0, 0, FW_NORMAL, 0, 0, 0, ANSI_CHARSET,\n   "
    "     OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY,\n        DEFAULT_PITCH | FF_DONTCARE, \"Segoe UI\");\n "
    "   if (lamo_gui.font) { SelectObject(lamo_gui.back_dc, lamo_gui.font); }\n    lamo_gui.is_open = 1;\n    return 1;\n}\n"
    "\nstatic int lamo_gui_should_close(void) {\n    lamo_gui_process_messages();\n    return lamo_gui.is_open ? 0 : 1;\n}\n"
    "\nstatic void lamo_gui_begin_frame(int r, int g, int b) {\n    RECT rect; HBRUSH brush;\n    if (!lamo_gui.is_open) retu"
    "rn;\n    rect.left = 0; rect.top = 0; rect.right = lamo_gui.width; rect.bottom = lamo_gui.height;\n    brush = CreateSol"
    "idBrush(RGB(r, g, b));\n    FillRect(lamo_gui.back_dc, &rect, brush);\n    DeleteObject(brush);\n}\n\nstatic void lamo_g"
    "ui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {\n    RECT rect; HBRUSH brush;\n    if (!lamo_gu"
    "i.is_open) return;\n    rect.left = x; rect.top = y; rect.right = x + width; rect.bottom = y + height;\n    brush = Crea"
    "teSolidBrush(RGB(r, g, b));\n    FillRect(lamo_gui.back_dc, &rect, brush);\n    DeleteObject(brush);\n}\n\nstatic void l"
    "amo_gui_draw_text(const char* text, int x, int y, int r, int g, int b) {\n    if (!lamo_gui.is_open) return;\n    SetTex"
    "tColor(lamo_gui.back_dc, RGB(r, g, b));\n    TextOutA(lamo_gui.back_dc, x, y, text, (int)strlen(text));\n}\n\nstatic voi"
    "d lamo_gui_end_frame(void) {\n    HDC window_dc;\n    if (!lamo_gui.is_open) return;\n    window_dc = GetDC(lamo_gui.hwn"
    "d);\n    BitBlt(window_dc, 0, 0, lamo_gui.width, lamo_gui.height, lamo_gui.back_dc, 0, 0, SRCCOPY);\n    ReleaseDC(lamo_"
    "gui.hwnd, window_dc);\n}\n\nstatic void lamo_gui_close(void) {\n    if (lamo_gui.font) { DeleteObject(lamo_gui.font); la"
    "mo_gui.font = NULL; }\n    if (lamo_gui.back_bitmap) { DeleteObject(lamo_gui.back_bitmap); lamo_gui.back_bitmap = NULL; "
    "}\n    if (lamo_gui.back_dc) { DeleteDC(lamo_gui.back_dc); lamo_gui.back_dc = NULL; }\n    if (lamo_gui.hwnd) { DestroyW"
    "indow(lamo_gui.hwnd); lamo_gui.hwnd = NULL; }\n    lamo_gui.is_open = 0;\n}\n#elif defined(__unix__) || defined(__unix) "
    "|| defined(__linux__) || defined(__APPLE__)\n/* Backend X11 for Linux/Mac. C and Xlib are trivial to link (-lX11). */\n#"
    "include <X11/Xlib.h>\n#include <X11/Xutil.h>\n#include <X11/Xos.h>\n\ntypedef struct {\n    Display* display;\n    Windo"
    "w window;\n    GC gc;\n    Pixmap back_pixmap;\n    XFontStruct* font;\n    int width;\n    int height;\n    int is_open"
    ";\n    Atom wm_delete;\n} LamoGuiState;\n\nstatic LamoGuiState lamo_gui = {0};\n\nstatic int lamo_gui_open(int width, in"
    "t height, const char* title) {\n    int screen;\n    if (lamo_gui.is_open) { return 1; }\n    lamo_gui.display = XOpenDi"
    "splay(NULL);\n    if (!lamo_gui.display) {\n        fprintf(stderr, \"failed to open X11 display\\n\");\n        return "
    "0;\n    }\n    screen = DefaultScreen(lamo_gui.display);\n    lamo_gui.width = width;\n    lamo_gui.height = height;\n  "
    "  lamo_gui.window = XCreateSimpleWindow(lamo_gui.display,\n        RootWindow(lamo_gui.display, screen),\n        0, 0, "
    "width, height, 1,\n        BlackPixel(lamo_gui.display, screen),\n        WhitePixel(lamo_gui.display, screen));\n    XS"
    "electInput(lamo_gui.display, lamo_gui.window,\n        ExposureMask | StructureNotifyMask);\n    XStoreName(lamo_gui.dis"
    "play, lamo_gui.window, title ? title : \"Lamo\");\n    lamo_gui.wm_delete = XInternAtom(lamo_gui.display, \"WM_DELETE_WI"
    "NDOW\", False);\n    XSetWMProtocols(lamo_gui.display, lamo_gui.window, &lamo_gui.wm_delete, 1);\n    lamo_gui.gc = XCre"
    "ateGC(lamo_gui.display, lamo_gui.window, 0, NULL);\n    lamo_gui.back_pixmap = XCreatePixmap(lamo_gui.display, lamo_gui."
    "window,\n        width, height, DefaultDepth(lamo_gui.display, screen));\n    lamo_gui.font = XLoadQueryFont(lamo_gui.di"
    "splay, \"fixed\");\n    if (lamo_gui.font) { XSetFont(lamo_gui.display, lamo_gui.gc, lamo_gui.font->fid); }\n    XMapWin"
    "dow(lamo_gui.display, lamo_gui.window);\n    XFlush(lamo_gui.display);\n    lamo_gui.is_open = 1;\n    return 1;\n}\n\ns"
    "tatic void lamo_gui_process_messages(void) {\n    XEvent event;\n    while (XPending(lamo_gui.display) > 0) {\n        X"
    "NextEvent(lamo_gui.display, &event);\n        if (event.type == ClientMessage) {\n            if ((Atom)event.xclient.da"
    "ta.l[0] == lamo_gui.wm_delete) {\n                lamo_gui.is_open = 0;\n            }\n        }\n    }\n}\n\nstatic in"
    "t lamo_gui_should_close(void) {\n    if (!lamo_gui.display) return 1;\n    lamo_gui_process_messages();\n    return lamo"
    "_gui.is_open ? 0 : 1;\n}\n\nstatic void lamo_gui_begin_frame(int r, int g, int b) {\n    XColor color;\n    if (!lamo_gu"
    "i.is_open) return;\n    color.red = (unsigned short)(r * 257);\n    color.green = (unsigned short)(g * 257);\n    color."
    "blue = (unsigned short)(b * 257);\n    color.flags = DoRed | DoGreen | DoBlue;\n    XAllocColor(lamo_gui.display, Defaul"
    "tColormap(lamo_gui.display, 0), &color);\n    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);\n    XFillRect"
    "angle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,\n        0, 0, lamo_gui.width, lamo_gui.height);\n}\n\nstatic"
    " void lamo_gui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {\n    XColor color;\n    if (!lamo_g"
    "ui.is_open) return;\n    color.red = (unsigned short)(r * 257);\n    color.green = (unsigned short)(g * 257);\n    color"
    ".blue = (unsigned short)(b * 257);\n    color.flags = DoRed | DoGreen | DoBlue;\n    XAllocColor(lamo_gui.display, Defau"
    "ltColormap(lamo_gui.display, 0), &color);\n    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);\n    XFillRec"
    "tangle(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.gc,\n        x, y, width, height);\n}\n\nstatic void lamo_gui_dr"
    "aw_text(const char* text, int x, int y, int r, int g, int b) {\n    XColor color;\n    if (!lamo_gui.is_open) return;\n "
    "   color.red = (unsigned short)(r * 257);\n    color.green = (unsigned short)(g * 257);\n    color.blue = (unsigned shor"
    "t)(b * 257);\n    color.flags = DoRed | DoGreen | DoBlue;\n    XAllocColor(lamo_gui.display, DefaultColormap(lamo_gui.di"
    "splay, 0), &color);\n    XSetForeground(lamo_gui.display, lamo_gui.gc, color.pixel);\n    XDrawString(lamo_gui.display, "
    "lamo_gui.back_pixmap, lamo_gui.gc,\n        x, y + (lamo_gui.font ? lamo_gui.font->ascent : 12),\n        text ? text : "
    "\"\", text ? (int)strlen(text) : 0);\n}\n\nstatic void lamo_gui_end_frame(void) {\n    if (!lamo_gui.is_open) return;\n "
    "   XCopyArea(lamo_gui.display, lamo_gui.back_pixmap, lamo_gui.window, lamo_gui.gc,\n        0, 0, lamo_gui.width, lamo_g"
    "ui.height, 0, 0);\n    XFlush(lamo_gui.display);\n}\n\nstatic void lamo_gui_close(void) {\n    if (lamo_gui.font) { XFre"
    "eFont(lamo_gui.display, lamo_gui.font); lamo_gui.font = NULL; }\n    if (lamo_gui.back_pixmap) { XFreePixmap(lamo_gui.di"
    "splay, lamo_gui.back_pixmap); lamo_gui.back_pixmap = 0; }\n    if (lamo_gui.gc) { XFreeGC(lamo_gui.display, lamo_gui.gc)"
    "; lamo_gui.gc = NULL; }\n    if (lamo_gui.window) { XDestroyWindow(lamo_gui.display, lamo_gui.window); lamo_gui.window ="
    " 0; }\n    if (lamo_gui.display) { XCloseDisplay(lamo_gui.display); lamo_gui.display = NULL; }\n    lamo_gui.is_open = 0"
    ";\n}\n#else\nstatic int lamo_gui_open(int width, int height, const char* title) {\n    (void)width; (void)height; (void)"
    "title;\n    fprintf(stderr, \"GUI builtins are not supported on this platform.\\n\");\n    return 0;\n}\nstatic int lamo"
    "_gui_should_close(void) { return 1; }\nstatic void lamo_gui_begin_frame(int r, int g, int b) { (void)r; (void)g; (void)b"
    "; }\nstatic void lamo_gui_draw_rect(int x, int y, int width, int height, int r, int g, int b) {\n    (void)x; (void)y; ("
    "void)width; (void)height; (void)r; (void)g; (void)b;\n}\nstatic void lamo_gui_draw_text(const char* text, int x, int y, "
    "int r, int g, int b) {\n    (void)text; (void)x; (void)y; (void)r; (void)g; (void)b;\n}\nstatic void lamo_gui_end_frame("
    "void) {}\nstatic void lamo_gui_close(void) {}\n#endif\n\n#endif /* LAMO_NEEDS_GUI_RUNTIME */\n\n/* ---------------------"
    "--------------------------------------------- */\n/* 3. HTTP runtime (only emitted when the program uses http_* builtins"
    ") */\n/* ------------------------------------------------------------------ */\n#ifdef LAMO_NEEDS_HTTP_RUNTIME\n\n#ifdef"
    " _WIN32\n#include <winsock2.h>\n#include <ws2tcpip.h>\ntypedef SOCKET lamo_socket_t;\n#define LAMO_INVALID_SOCKET INVALI"
    "D_SOCKET\n#define lamo_close_socket closesocket\n#else\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netin"
    "et/in.h>\n#include <arpa/inet.h>\n#include <unistd.h>\ntypedef int lamo_socket_t;\n#define LAMO_INVALID_SOCKET (-1)\n#de"
    "fine lamo_close_socket close\n#endif\n\ntypedef struct LamoHttpRoute {\n    char* path;\n    char* body;\n    struct Lam"
    "oHttpRoute* next;\n} LamoHttpRoute;\n\nstatic LamoHttpRoute* lamo_http_routes = NULL;\nstatic int lamo_http_runtime_init"
    "ialized = 0;\n\nstatic int lamo_http_init_runtime(void) {\n#ifdef _WIN32\n    WSADATA wsa_data;\n    if (!lamo_http_runt"
    "ime_initialized) {\n        if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {\n            fprintf(stderr, \"failed to i"
    "nitialize Winsock\\n\");\n            return 0;\n        }\n        lamo_http_runtime_initialized = 1;\n    }\n#else\n  "
    "  lamo_http_runtime_initialized = 1;\n#endif\n    return 1;\n}\n\nstatic void lamo_http_add_route(const char* path, cons"
    "t char* body) {\n    LamoHttpRoute* route;\n    if (!lamo_http_init_runtime()) { return; }\n    route = malloc(sizeof(La"
    "moHttpRoute));\n    if (!route) { fprintf(stderr, \"failed to allocate HTTP route\\n\"); exit(1); }\n    route->path = l"
    "amo_heap_strdup(path);\n    route->body = lamo_heap_strdup(body);\n    route->next = lamo_http_routes;\n    lamo_http_ro"
    "utes = route;\n}\n\nstatic const LamoHttpRoute* lamo_http_find_route(const char* path) {\n    LamoHttpRoute* current = l"
    "amo_http_routes;\n    while (current) {\n        if (strcmp(current->path, path) == 0) { return current; }\n        curr"
    "ent = current->next;\n    }\n    return NULL;\n}\n\nstatic int lamo_http_send_all(lamo_socket_t socket_fd, const char* d"
    "ata, int total_length) {\n    int sent = 0;\n    while (sent < total_length) {\n        int chunk = send(socket_fd, data"
    " + sent, total_length - sent, 0);\n        if (chunk <= 0) { return 0; }\n        sent += chunk;\n    }\n    return 1;\n"
    "}\n\nstatic int lamo_http_send_response(lamo_socket_t client_socket, int status_code, const char* body) {\n    char head"
    "er[512];\n    const char* reason = status_code == 200 ? \"OK\" : \"Not Found\";\n    int body_length = (int)strlen(body)"
    ";\n    int header_length = snprintf(header, sizeof(header),\n        \"HTTP/1.1 %d %s\\r\\n\"\n        \"Content-Type: t"
    "ext/plain; charset=utf-8\\r\\n\"\n        \"Content-Length: %d\\r\\n\"\n        \"Connection: close\\r\\n\\r\\n\",\n    "
    "    status_code, reason, body_length);\n    if (header_length < 0 || !lamo_http_send_all(client_socket, header, header_l"
    "ength)) {\n        return 0;\n    }\n    return lamo_http_send_all(client_socket, body, body_length);\n}\n\nstatic void "
    "lamo_http_handle_client(lamo_socket_t client_socket) {\n    char request[2048];\n    char method[16];\n    char path[102"
    "4];\n    int received = recv(client_socket, request, (int)sizeof(request) - 1, 0);\n    if (received <= 0) { return; }\n"
    "    request[received] = '\\0';\n    method[0] = '\\0';\n    path[0] = '\\0';\n    if (sscanf(request, \"%15s %1023s\", m"
    "ethod, path) == 2) {\n        const LamoHttpRoute* route = lamo_http_find_route(path);\n        if (route) {\n          "
    "  lamo_http_send_response(client_socket, 200, route->body);\n            return;\n        }\n    }\n    lamo_http_send_r"
    "esponse(client_socket, 404, \"not found\");\n}\n\nstatic int lamo_http_run_server(int port, int serve_once) {\n    lamo_"
    "socket_t server_socket;\n    struct sockaddr_in address;\n    int opt_value = 1;\n    if (!lamo_http_init_runtime()) { r"
    "eturn 0; }\n    server_socket = socket(AF_INET, SOCK_STREAM, 0);\n    if (server_socket == LAMO_INVALID_SOCKET) {\n     "
    "   fprintf(stderr, \"failed to create HTTP socket\\n\");\n        return 0;\n    }\n    setsockopt(server_socket, SOL_SO"
    "CKET, SO_REUSEADDR, (const char*)&opt_value, sizeof(opt_value));\n    memset(&address, 0, sizeof(address));\n    address"
    ".sin_family = AF_INET;\n    address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n    address.sin_port = htons((unsigned sh"
    "ort)port);\n    if (bind(server_socket, (struct sockaddr*)&address, sizeof(address)) != 0) {\n        fprintf(stderr, \""
    "failed to bind HTTP server on port %d\\n\", port);\n        lamo_close_socket(server_socket);\n        return 0;\n    }"
    "\n    if (listen(server_socket, 8) != 0) {\n        fprintf(stderr, \"failed to listen on HTTP server port %d\\n\", port"
    ");\n        lamo_close_socket(server_socket);\n        return 0;\n    }\n    while (1) {\n        lamo_socket_t client_s"
    "ocket = accept(server_socket, NULL, NULL);\n        if (client_socket == LAMO_INVALID_SOCKET) { break; }\n        lamo_h"
    "ttp_handle_client(client_socket);\n        lamo_close_socket(client_socket);\n        if (serve_once) { break; }\n    }"
    "\n    lamo_close_socket(server_socket);\n    return 1;\n}\n\n#endif /* LAMO_NEEDS_HTTP_RUNTIME */\n\n#endif /* LAMO_RUNT"
    "IME_H */\n"
;
